### ISSUE TITLE
Scan-Activity-Layout

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#1]
Beim Scannen sollte das Layout (13-qr.png) wie von Matthias vorgeschlagen verwendet werden.

Als Text würde ich statt (Beim Scannen bitte ruhig halten) schreiben.
Scanne den QR-Code des CheckPoints!

**Comment by skienzl** [comment]
Hier ist die ganze "Kamera Fläche" zum Scannen da. Deswegen ist das Layout nur begrenzt umsetzbar. Leider kann ich auch die Kamera nicht unter die ActionBar schieben, weil sie sonst verzehrt.
