### ISSUE TITLE
Bikebirds oder BIKEbirds

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#100]
Eine Frage an den Ästheten.

Sollen wir die schnuckeligen radelnden Vögel BIKEbirds oder Bikebirds nennen?

**Comment by starflower** [comment]
Nachdem es ja BIKEline heißt ist das eher eine Markengeschichte. Ich würd's vermutlich BIKEbirds benennen, damit wir in der Marke einheitlich auftreten. Obwohl ich die Variante BikeBirds auch ok find :abc: 

BIKEline
BIKEbirds
BikeBirds
Bikebirds
BB

**Comment by Didi71** [comment]
dann nennen wir's

BIKEbirds

Stefan könntest du das dann bitte noch ändern bei

BIKEbirds & Preise

bzw. am Hauptscreen.

Danke

Am 08.08.2013 09:09, schrieb Matthias Kampitsch:
