### ISSUE TITLE
CheckPoints - Infobox

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#101]
Im Vergleich zu den übrigen graphischen Element schaut die Infobox zur Auswahl der Webpage ("Öffne Webpage ...") noch etwas holprig und grob aus.

Kannst da noch mal bitte drübergehen?

**Comment by starflower** [comment]
Ich würde den Dialog so gestalten wie die bei der Team-Auswahl. Geht das @skienzl ?

**Comment by skienzl** [comment]
geht :)

**Comment by starflower** [comment]
Freut mich!
