### ISSUE TITLE
Preis gewonnen Screen

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#104]
Ich würde gern das Event, bei dem ein Biker einen Preis gewonnen hat noch besser darstellen. Mein Vorschlag wäre deshalb als Überschrift das Event zu bringen.

und das "Herzlichen Glückwunsch!" weiter unten vor der Preisbeschreibung

Matthias?

![rf](https://f.cloud.github.com/assets/5090129/929667/0916c2dc-ffee-11e2-85b7-6d0bc0fef5d5.jpg)

**Comment by starflower** [comment]
Finde ich auch ok so :) Entwurf hast Du ja schon gemacht :P
