### ISSUE TITLE
Bikebirds & Preise - Message Boxes

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#110]
Es ist ein bisschen verwirrent, dass wenn man z.B. auf den Preise-Tab tippt eine Messagebox "Lade Bundesländer ..." angezeigt wird.

Können wir das Vorabladen von Tab nicht sein lassen, und den aktuellen Tab immer dann laden wenn er das erste Mal aufgerufen wird.

**Comment by skienzl** [comment]
das "Lade BIKEline-Bundesländer ..." kommt jetzt nicht mehr. also passt das somit od?

**Comment by Didi71** [comment]
Was passiert wenn man auf wähle Bundesland tippt und die Bundesländer noch nicht geladen sind?

Am 08.08.2013 um 11:19 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
dann is die box noch nicht da. und de 8 strings sollten normal extrem schnell fertig sein :) das sind ja nur ein paar byte. würde mich wundern wenn einer einmal so schnell ist :D

**Comment by Didi71** [comment]
Ok

Am 08.08.2013 um 11:29 schrieb skienzl notifications@github.com:
