### ISSUE TITLE
Messages wenn Server nicht erreichbar.

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#118]
Wenn der BIKEline Server nicht erreichbar ist, oder aber auch wenn das Handy keinen Internetzugang hat, dann sollten wir entsprechend darauf reagieren.

Bei den CheckPoints wird zwar die Map angezeigt, aber die CheckPoints nicht.
Der CheckIn bleibt hängen.
Bei BIKEbirds & Preise werden teilweise keine Werte angezeigt.
Team beitreten - da werden die Auswahllisten nicht ausgefüllt.

Vorschlag wenn keine Internetverbindung vorhanden:
CheckPoints: MessageBox: 
   Überschrift: "Keine Internetverbindung"
   Text: "Zum Anzeigen der CheckPoints benötigst du eine Internetverbindung."
   Button: "Ok"
CheckIn: MessageBox: 
   Überschrift: "Keine Internetverbindung"
   Text: "Zum Einchecken benötigst du eine Internetverbindung."
   Button: "Ok"
Team beitreten: 
   Option im Menü und unter BIKEbirds&Preise nur anzeigen, wenn Internetverbindung 
   vorhanden
BIKEbirds & Preise:
   bitte die BIKEbirds und den Rang auch in der App speichern und wenn kein  
   Internet verfügbar ist anzeigen.

Bei BIKEbirds & Preise sollten wir einen Toast anzeigen, wenn keine Internetverbindung besteht.

```
Überschrift: "Keine Internetverbindung"
Text: "Derzeit besteht keine Internetverbindung. Die angezeigten Infos sind 
         deshalb möglicherweise nicht am letzten Stand."
```

**Comment by skienzl** [comment]
auch die team liste sollte nur angezeit werden wenn internet da ist od? die daten sollten ja auch aktuell sein denke ich mir

**Comment by skienzl** [comment]
das gleiche gilt auch für profil bearbeiten. macht auch keinen sinn das zu bearbeiten wenn man es nicht hochladen kann
