### ISSUE TITLE
Bereits Mitglied - MessageBox

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#121]
Wenn man sich anmelden will und man auf "Bereits Mitglied?" drückt, dann sollte folgende MessageBox angezeigt werden

Überschrift: Keine Internetverbindung
Text: Zum Anmelden benötigst du eine Internetverbindung.
Button: Ok

Nachdem der User auf "Ok" gedrückt hat, sollte er zum Start-Screen zurückkehren.

**Comment by skienzl** [comment]
warum sollte man dann zum start-screen zurück kommen?

**Comment by Didi71** [comment]
Weil man sich ohnehin nicht anmelden kann.

Am 10.08.2013 um 09:58 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
dann könnte ich die app auch gleich schließen. ich denke wahrscheinlicher ist das man gerade das mobile internet deaktiviert hat und es nur einschalten muss. wenn das der fall ist muss ich noch einmal alles eingeben (speziell beim registrieren ist das lästig) obwohl ich nur das mobile internet einschalten müsste und alles passt

**Comment by Didi71** [comment]
Ok! Passt wir bleiben an Anmeldescreen

Am 10.08.2013 um 10:14 schrieb skienzl notifications@github.com:
