### ISSUE TITLE
CheckIn ungültige QR-Codes

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#128]
Beim Lesen eines nicht registrierten QR-Codes sollte eine Fehlermeldung (wie z.B. "Dieser CheckPoint ist nicht aktiv." ausgegeben werden.
Stattdessen passiert nix!

**Comment by skienzl** [comment]
meinst du jetzt einen "ungültige" od "nicht registrierten" QR Code? 
den bei INVALID_CHECKPOINT kommt:
CheckIn fehlgeschlagen - Der gescannte CheckPoint ist deaktiviert!

**Comment by Didi71** [comment]
Ja, checkIn.php liefert ein INVALID_CHECKPOINT - und die App bleibt auf 
meinem Samsung hängen

Am 08.09.2013 20:43, schrieb skienzl:

**Comment by skienzl** [comment]
leider kann ich den fehler bei mir nicht produzieren. sowohl bei INVALID_CHECKPOINT als auch wenn der QR code garnicht von bikeline kommt, kommt eine msg box die sagt was nicht passt. 
stürzt die app bei dir dann ab?

**Comment by Didi71** [comment]
nein - sie stürzt nicht ab - macht aber auch nix.

**Comment by skienzl** [comment]
kannst du mir den QR code schicken mit dem du das getestet hast?

**Comment by Didi71** [comment]
anbei eine Reihen von Stickern.
Mit Ausnahme CP13432339 sollte keiner Funktionieren und den Fehler 
hervorrufen.

Am 09.09.2013 15:53, schrieb skienzl:

**Comment by skienzl** [comment]
kann es sein das der server in dem fall eine leere antwort gibt?

**Comment by Didi71** [comment]
Oha - verd....

du hast recht - im Falle eines INVALID_CHECKPOINT gab der Server nix zurück.
Jetzt sollt's gehen - oder?

LG
Didi

Am 09.09.2013 17:04, schrieb skienzl:

**Comment by skienzl** [comment]
schaut gut aus :)
