### ISSUE TITLE
Map - Raiffeisenbank Oberes Lavanttal

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#129]
Als Event wir "null" angezeigt, obwohl für es für diesen CheckPoint gar kein Event gibt.
Er wird auch nicht als Hot angezeigt.

**Comment by skienzl** [comment]
Also das kommt vom server beim checkpoint "Raiffeisenbank Oberes Lavanttal", mit isHot=false 
{
            "id": 13432024,
            "name": "Raiffeisenbank Oberes Lavanttal",
            "webPage": "http://www.raiffeisen.at/",
            "city": "Bad St. Leonhard",
            "latitude": 46.9613387,
            "longitude": 14.7952193,
            "isHot": false,
            "eventName": null,
            "eventWebPage": null,
            "eventStart": 0,
            "eventEnd": 0
        },

**Comment by Didi71** [comment]
passt.

aber wenn isHot=false ist, dann sollte der EventName im InfoFenster 
nicht angezeigt werden.
Bei der Raiba wird da "null" angezeigt.

Am 08.09.2013 20:47, schrieb skienzl:

**Comment by skienzl** [comment]
aber "Raiffeisenbank Oberes Lavanttal" ist im normalen "name" und nicht im "eventName" drin. also passt das danke ich od? 
das mit dem null check ich gerade

**Comment by Didi71** [comment]
Hm!

I glaub I spinn - jetzt wird die Raiba richtig angezeigt.
Früher würde, obwohl sie nicht hot war auch der EventName angezeigt, und 
der war null.

Komisch!

Am 08.09.2013 21:08, schrieb skienzl:
