### ISSUE TITLE
Einem Team beitreten

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#13]
Titel ändern und verschieben in den ActionBar: Team beitreten

Erster Absatz: beitreten.
Zweiter + Dritter Absatz: nicht einrücken
Dritter Absatz: im Text "Keinem Team beitreten" löschen und statt dessen den Button "Keinem Team beitreten" unter dem 3. Absatz platzieren.

Ablauf Teamauswahl.
1.) Bundesland
2.) Schule
3.) SchülerIn
Sobald eine SchülerIn gewählt wurde bitte einen Button "Team beitreten" anzeigen und NICHT automatisch weitergehen.

**Comment by starflower** [comment]
Grund für die Platzierung des "Keinem Team beitreten"-Buttons unter den Auswahlfeldern: 
Das soll hier nicht die Nr.1 Aktion sein. Hier soll man einem Team beitreten. Wenn nicht, kann man immer ans Ende scrollen und keinem Team beitreten. Auf kleineren Screens kann auch passieren, dass die Felder durch den langen Text ohne Scrollen gar nicht sichtbar sind.

**Comment by skienzl** [comment]
also button "Team beitreten" ist jetzt da. wegen dem anderen button müsst ihr noch sagen wie das sein soll.

**Comment by Didi71** [comment]
@Matthias: So wie der Screen jetzt aussieht leuchtet unten immer der Button "Keinem Team beitreten".
Könnte man das als Link in den 3. Absatz einpflegen.

z.B. Wähle nun entweder den BIKEliner, dessen Team du beitreten möchtest, oder drücke auf "Keinem Team beitreten"   ... und keinem Team beitreten ist ein in den Text eingebundener Minifuzibutton.

**Comment by starflower** [comment]
Das wär natürlich noch schöner.

**Comment by skienzl** [comment]
ist so umgesetzt :)

**Comment by starflower** [comment]
den Link noch in weiß, dann ist's perfekt :)
