### ISSUE TITLE
Team beitreten - keine Schüler

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#130]
Wenn man einem Team beitreten möchte und ein Bundesland und eine Schule gewählt hat und keine Schüler vorhanden sind, dann wir "Laden fehlgeschalgen" ausgegeben.

Ungeachtet des Tippfehlers sollte besser die Meldung "An dieser Schule gibt es heuer noch keine BIKEliner." ausgegeben werden.

**Comment by skienzl** [comment]
ist es da nicht besser wenn eine schule ohne schüler garnicht angezeigt wird? also garnicht vom server mitgeschickt wird? macht doch keinen sinn wenn sie mitgeschickt wird obwohl man e schon weis das da kein schüler registriert ist.

**Comment by clueckler** [comment]
Meiner Meinung nach auch entweder gleich ausblenden und nicht mitschicken, oder Server soll einen ErrorCode aussenden! So eine Auswertung sollte nicht von der App gemacht werden!

**Comment by Didi71** [comment]
Ok!

Im schlimmsten Fall könnte aber sein, dass es noch gar keine Schüler an 
keiner Schule gibt.
Dann gibt getProvices eine leere Liste zurück.
In diesem Fall sollte dann die Fehlermeldung ausgegeben werden:

"Es sind noch keine BIKEliner registriert die du unterstützen könntest."

Am 08.09.2013 20:56, schrieb Christoph Lückler:

**Comment by skienzl** [comment]
wenn es noch keinen schüler gibt dann sollte ja auch keine eintrag für die schule kommen. weiters sollte auch das bundesland nicht übermittelt werden falls es keine schule gibt.

**Comment by Didi71** [comment]
ja - ich hab jetzt einen einzigen Schüler eingetragen. jetzt sollte 
lediglich die Steiermark, Fürstenfeld und ein BIKEliner erscheinen.
Ich wollt's grade testen, aber jetzt schmiert die App immer ab.

Am 08.09.2013 21:17, schrieb skienzl:

**Comment by Didi71** [comment]
Ja! Hab grad die Server-Skripte aktualisiert.

Das Bundesland liefert jetzt aktuell eine leere Liste. Die App zeigt 
derzeit an "Laden fehlgeschlagen ...".
Besser wäre sicherlich wenn in diesem Fall ein Screen mit anderem Text 
angezeigt wird.

z.B.

Einem Team beitreten

Es gibt derzeit keine BIKEliner die du unterstützen könntest.

Am 08.09.2013 21:17, schrieb skienzl:

**Comment by skienzl** [comment]
es kommt derzeit als fehlercode 255 zurück wenn die liste leer ist. also kommt dann immer der von dir geschrieben text in dem fall?

**Comment by Didi71** [comment]
das ist natürlich ein Blödsinn.

Hab's umgebaut. Jetzt sollte OK zurückgeliefert werden.
Lediglich die Liste ist leer.

Am 08.09.2013 21:45, schrieb skienzl:
