### ISSUE TITLE
bei INVALID_CHECKPOINT trotzdem erhöhung der bikebirds

### ISSUE THREAD

**Issue by skienzl** [Didi71/BIKELine-Android_old_tbd#138]
mit ist aufgefallen das obwohl der fehlercode für INVALID_CHECKPOINT zurückkommt, sich die anzahl der bikebirds erhöht. sollte nicht so sein od?

**Comment by Didi71** [comment]
oha - danke für den Hinweis - ist jetzt korrigiert.

Am 09.09.2013 17:33, schrieb skienzl:
