### ISSUE TITLE
Team beitreten - Auswahllisten

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#14]
Den Hintergrund der Auswahllisten bitte in der Farbe der Buttons darstellen.
Die Auswahlliste sollte so breit wie der Button "Keinem Team beitreten" sein.

**Comment by starflower** [comment]
Du meinst das Dropdown hier im Anhang? Da wollt ich sowieso noch mit Stefan drüberschaun.
![screenshot_2013-07-31-10-45-26](https://f.cloud.github.com/assets/499926/884694/c3c8fd8e-f9bd-11e2-8488-be9956120b9b.png)

**Comment by Didi71** [comment]
ja - das hatte ich gemeint
