### ISSUE TITLE
Keine Internetverbindung - Einchecken

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#140]
Wenn beim Einchecken keine Internetverbindung verfügbar ist, dann wird deine Messagebox angezeigt.

Der Okay-Button dieser MessageBox ist sehr sehr sehr hoch - bitte korrigieren.

**Comment by skienzl** [comment]
könntest du mir da einen screenshot schicken? kann den fehler bei mir nicht hervorrufen

**Comment by Didi71** [comment]
tritt bei meinen Samsung Galaxy S3 mini auf.

![image](https://f.cloud.github.com/assets/5090129/1160228/d1911c92-1fd5-11e3-8087-f7545ee01505.png)

**Comment by skienzl** [comment]
also ist das bei allen popups so?

**Comment by Didi71** [comment]
Ja, grad' getestet.

Beim Samsung Galayxy S3 mini - passiert das bei jedem Popup.

Am 21.09.2013 17:40, schrieb skienzl:

**Comment by Didi71** [comment]
duplicate issue
