### ISSUE TITLE
Value1 in Circles

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#148]
Es gibt einige Screentypen, die Zahlen in Kreisen darstellen. Meist können in den Kreisen zwei Werte dargestellt werden (z.B. value1_1 und value1_2). Wenn nur ein Wert angegeben wird, dann sollte dieser Wert mittig im Kreis angezeigt werden.

**Comment by skienzl** [comment]
da müsste ich jetzt wieder alles durchgehen und 2 extra layouts bei allen machen!! bitte solche infos früher...

**Comment by Didi71** [comment]
Sorry, ich dachte da müsstest du lediglich die Textausgabe ein bisschen nach unten verschieben.

Am 14.10.2013 um 00:20 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
ich denke wenn nur 1 wert drin steht wird es nur value_1 sein oder?

**Comment by Didi71** [comment]
Ja

Am 14.10.2013 um 10:41 schrieb skienzl notifications@github.com:
