### ISSUE TITLE
Team bearbeiten - Initialisierung

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#15]
Wenn man bereits einem Team beigetreten ist, dann sollten bei nochmaligem Aufruf von "Team bearbeiten", die Listen bereits ausgefüllt bzw. vorgewählt sein.

**Comment by clueckler** [comment]
Dazu braucht es einen neuen API-Befehlt getTeam.php

**Comment by Didi71** [comment]
Nö - ist nicht nötig. Das geht auch mit getProvinces.php, getOrgs.php und getBikers.php.
Wenn einem Team beigetreten wurden, dann getProvinces.php aufrufen und die gewählte Province in der Liste wählen. Danach getOrgs.php aufrufen und die entsprechende Schule in der Liste wählen, und zuletzt getBikers ...

**Comment by clueckler** [comment]
Dadurch werden unnötige Daten lokal abgespeichert (Province / Organisation). Sollte sich bei Province auch nur ein Buchstabe ändern, kann dies die Funktion des automatischen Ausfüllens zerstören.

**Comment by skienzl** [comment]
Da es ja nicht möglich ist von der TeamID auf Schule und Bundesland zu schließen. Dann muss ich zur TeamID das Bundesland und Schule abspeichern. Weil von der TeamID komme ich sonst nur durch probieren aller Kombinationen zur Auswahl.
Also geht das oben beschriebene so nicht einfach über getProvince und getOrgs zur TeamID.

**Comment by Didi71** [comment]
ich werd' mal schnell ein getTeam.php Skript basteln.

**Comment by Didi71** [comment]
getTeam.php ist jetzt verfügbar

**Comment by Didi71** [comment]
das bitte noch einbauen.

**Comment by skienzl** [comment]
sollte jetzt passen ;)
