### ISSUE TITLE
Sleep - Problem

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#155]
Wenn das Phone in Sleep geht (Bildschirm wird dunkel), man aber kurz zuvor noch den Server kontaktiert hat, dann bleibt der Request, wenn das Handy dann wieder aufgewacht ist, stecken.

**Comment by skienzl** [comment]
is das noch bei der map?

**Comment by skienzl** [comment]
kannst du das bei der map checken? ob das immer noch so ist?

**Comment by Didi71** [comment]
Scheint jetzt zu gehen - komisch ist allerdings, das wenn ich die Map wähle, das Phone dann in sleep geht, und ich danach das Phone wieder aufwecke - die App. nochmals die CheckPoints lädt. Das müsste eigentlich nicht sein oder?
