### ISSUE TITLE
CheckPoints Anzeige doppelt

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#158]
Wenn sich ein CheckPoint ändert, z.B. neuer Marker, dann wird er doppelt angezeigt.

**Comment by skienzl** [comment]
ich denke dann hat er nicht mehr die gleiche ID bei dir :) wenn die ID anders ist dann wird er doppelt angezeigt :)

**Comment by Didi71** [comment]
nö - die ID ist definitiv die Selbe.
Ich werd's nochmal mit V9 testen.

Am 22.10.2013 18:54, schrieb skienzl:
