### ISSUE TITLE
CheckPoints werden nicht aktualisiert

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#161]
Als Operation wird 'new' zurückgegeben, aber die CheckPoints werden nicht aktualisiert, wenn z.B. der Marker geändert wird.

**Comment by skienzl** [comment]
warum sollte bei "new" etwas aktualisiert werden? dafür gibt es doch update

**Comment by Didi71** [comment]
Bei New sind alle Daten neu, und alte in der App gespeicherte sollten gelöscht werden.

Bei Update wird nur aktualisiert, jene Checkpoints für die keine Infos geschickt werden, bleiben unverändert.

Am 23.10.2013 um 09:35 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
ich verstehe den sinn bei den beiden operations nicht ganz. kannst du mich da einmal anrufen wenn du zeit hast

**Comment by Didi71** [comment]
lass' es uns so machen wie definiert.

ein "update" bei einem CheckPoint kann bedeuten, dass der CheckPoint 
entweder neu anzulegen oder zu aktualisieren ist.
Eine größere Menge von "neuen" CheckPoints ist nur beim ersten Aufruf zu 
erwarten. In diesem Fall kannst du alle zurückgelieferten CheckPoints 
("schnell" als neue CheckPoints) importieren. Bei den folgenden Aufrufen 
sind ohnehin nur kleinere Änderungen zu erwarten; da spielt die Zeit 
dann keine so große Rolle.

Am 23.10.2013 12:07, schrieb skienzl:
