### ISSUE TITLE
Hintergrundbilder - Seitenverhältnis

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#162]
Bei Hintergrundbildern sollte das Seitenverhältnis gewahrt bleiben.

**Comment by skienzl** [comment]
also sollte ich dir die genauen maße von display mitschicken? dann könntest du sie am server schon richtig anpassen

**Comment by Didi71** [comment]
Das wär auch eine Möglichkeit, können wir gern so machen. Sag mir nur, welche Parameter du schickst.

Am 26.10.2013 um 15:15 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
einfach die breite und höhe des displays in pixel

**Comment by Didi71** [comment]
dann nennen wir die parameter width und height

Am 27.10.2013 15:34, schrieb skienzl:

**Comment by skienzl** [comment]
es kommt nur ein schwarzer bg. ist das korrekt?

**Comment by Didi71** [comment]
Nö, muss mal gucken.

Am 27.10.2013 um 17:08 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
welches skript rufst du auf, und mit welchen parametern?

Am 27.10.2013 17:08, schrieb skienzl:

**Comment by skienzl** [comment]
http://www.bikebird.at/BIKElineCheckPoint/TestApp-Scripts/getResourceV2.php

mit den folgenden parameter: 

![bildschirmfoto 2013-10-27 um 18 28 00](https://f.cloud.github.com/assets/4992387/1415985/2b5fbe7e-3f2d-11e3-89db-b274fa53765d.png)

**Comment by Didi71** [comment]
aha!

ich hab', auf dein anraten am Server aufgeräumt und allen Hintergründen 
den Prefix "bg_" verpasst.
deshalb heisst der Hintergrund jetzt auch bg_background1.jpg.

Ich dachte, ich hätte das in allen Skripten angepasst. Hab' ich's 
irgendwo vergessen?

Am 27.10.2013 18:28, schrieb skienzl:

**Comment by skienzl** [comment]
hab da noch mit dem alten getFactsV2-Test.php getestet. deswegen kam das da anscheinend :)

**Comment by skienzl** [comment]
nein. hab sogar schon mit dem richtigen aufgerufen. kommt aber immer noch schwarz leider!

**Comment by skienzl** [comment]
width = 480
height = 800
fileName = bg_background2.jpg
type = background
resolution = hdpi

**Comment by Didi71** [comment]
kannst bitte nochmal versuchen.

Am 27.10.2013 18:36, schrieb skienzl:

**Comment by skienzl** [comment]
leider noch immer. hab es auch mit dem tool getestet. da kommt auch nur ein schwarzes bild raus: http://www.motobit.com/util/base64-decoder-encoder.asp

**Comment by Didi71** [comment]
lokal geht's - muss grad' was am Server testen - getResourceV2.php wird 
deshalb kurzzeitig gar nicht funktionieren.

Am 27.10.2013 18:53, schrieb skienzl:

**Comment by Didi71** [comment]
Also ganz verstehen tu ich's nicht.

wenn ich
http://www.bikebird.at/BIKElineCheckPoint/TestApp-Scripts/getResourceV2.php?type=background&fileName=bg_background1.jpg&resolution=hdpi&width=480&height=800
aufrufe, dann convertiert mir deine Seite von unten die Base64 Daten 
richtig in eine JPEG Datei.
Ich hab' mir aber am Server eine temporäre Datei erzeugt, die als Basis 
dienen soll - die wird aber nicht erzeugt ???

kannst es bitte nochmal versuchen?

Am 27.10.2013 18:53, schrieb skienzl:

**Comment by skienzl** [comment]
hast du vl einen unterschied von GET und POST?

**Comment by skienzl** [comment]
jetzt gehts!!!

**Comment by Didi71** [comment]
nö - hab's für's erste mal so gemacht, dass, wenn ein GET vorhanden ist, 
der den POST überschreibt

Am 27.10.2013 20:55, schrieb skienzl:
