### ISSUE TITLE
getFactsV2-Test.php - screens not deleted

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#163]
screens that are not included in the response don't get deleted

**Comment by skienzl** [comment]
war auch nie so ausgemacht ;) sondern mit einem "delete" befehl!!

**Comment by Didi71** [comment]
bei getFactsV2.php hab' ich seineerzeit definiert:

```
    "operation": ...             the operation to be performed on this screen
                                  ok       = nothing needs to be done
                                  new      = data of screen are completely new
                                  update   = data of screen shall be updated; only data newer than timestamp
                                             are transmitted
                                  delete   = delete a screen
                                  NOTE: if the app sends a screenId, and this screenId is not included in this
                                  response, then the screen is to be deleted in the app.
```

d.h. wenn z.B. new zurückgegeben wird, dann sind die Daten des Screens 
neu zu übernehmen, wenn ein update kommt, dann sind die Daten 
anzuhängen, wenn ein ok kommt, dann gibt's nix Neues.

delete haben wir hier zwar definiert, aber die NOTE darunter sagt, dass 
wenn ein Screen zwar in der ScreenId drinnen ist die du schickst, ich 
den Screen aber nicht zurück schicke, dann ist der Screen zu löschen.

"delete" wäre somit gar nicht nötig.

Am 26.10.2013 13:22, schrieb skienzl:

**Comment by Didi71** [comment]
derzeit liefert getFactsV2-Test.php die Screens übrigens immer mit operation="new" zurück.
"update" bzw. "ok" muss ich erst implementieren.

**Comment by skienzl** [comment]
mich bitte über solche änderungen informieren. aber es ist leichter für mich wenn du den delete befehl gibts. dann muss ich nicht ständig überprüfen ob ich den screen jetzt habe oder nicht. und die api sollte sich auch schon fixieren weil ich doch schon einige änderungen umsonst gemacht habe!! das ist alles zeit die umsonst ist!!

**Comment by Didi71** [comment]
sorry - ich dachte, dass du da ein Mail kriegst, wenn ich was ändere.

OK, dann nehm ich die NOTE raus, und schick ein DELETE.

Ein Fehler ist aber trotzdem noch drin, weil bei einer Operation="new" 
die Daten der Screens nicht vollständig übernommen werden.

Am 26.10.2013 13:40, schrieb skienzl:
