### ISSUE TITLE
getFactsV2-Test.php + group_icon_inactive

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#165]
Wenn eine Gruppe nicht aktive ist, sollte das "group_icon_inactive" icon angezeigt werden.

**Comment by skienzl** [comment]
was heißt nicht aktiv?

**Comment by Didi71** [comment]
es gibt ja immer eine gruppe die angezeigt wird, die übrigen sind 
inaktiv und hatten bei der alten Version ein anderes Icon

Am 26.10.2013 13:21, schrieb skienzl:

**Comment by skienzl** [comment]
was haltest du davon wenn ich bei mir die icons automatisch transparent mache wenn sie nicht aktiv sind? dann musst du nicht imemr 2 icons mitschicken.

**Comment by skienzl** [comment]
und für xxhdpi sind noch keine resources hinterlegt oder?

**Comment by Didi71** [comment]
Perfekt. Mach ma so

Am 26.10.2013 um 15:07 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
Nö, da muss ich Matthias mal bitten ...

Am 26.10.2013 um 15:08 schrieb skienzl notifications@github.com:
