### ISSUE TITLE
CheckPoints - Farben der Marker

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#168]
Irgendwie werden seit der letzten Version immer nur blaue Marker angezeigt.

**Comment by skienzl** [comment]
das ist weil du anscheinend bei getResourceV2.php immer width und height brauchst, sonst kommt zuerst eine fehlermeldung. auch wenn es kein bg ist. deswegen kann ich die daten nicht interpretieren.

**Comment by Didi71** [comment]
oha ... das muss ich dann korrigieren - tschuldigung!

Am 29.10.2013 23:00, schrieb skienzl:

**Comment by Didi71** [comment]
war ich selbst - depp
