### ISSUE TITLE
CheckPoint - Cluster Marker

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#169]
Der Standard cluster-marker sollte: ic_map_pin_cluster.png sein.

ic_map_pin_cluster_mix.png hatte ich mal angedacht, wenn innerhalb eines Clusters Marker angezeigt werden die nicht blau sind.

Wäre es möglich das Cluster-Icon abhängig von den sich in ihm befindlichen Markern anzuzeigen. Soll heissen, wenn alle Marker innerhalb des Clusters grau (markerGrey.png) sind, dann sollte ein grauer Cluster (cluster-markerGrey.png) angezeigt werden, sind alle blau (markerBlue.png), dann -> Cluster (cluster-markerBlue.png, und wenn unterschiedliche Markerfarben vertreten sind -> Cluster (cluster-mix.png) ?

**Comment by skienzl** [comment]
möglich wäre es schon. nur der cluster wird dann denke ich langsamer. jedoch nicht schlimm denke ich. aber macht das sinn so viel farbe rein zu bringen? wäre ein neutraler cluster nicht besser?

**Comment by Didi71** [comment]
war meinst zu mit neutraler cluster?

Am 29.10.2013 23:24, schrieb skienzl:

**Comment by skienzl** [comment]
neutralen cluster marker. 
aber wir können auch verschiedene machen. sollte gehen

**Comment by Didi71** [comment]
hab's grad in getResourceV2.php dokumentiert.
Schau mal bitte kurz drauf, ob das verständlich ist.

Am 29.10.2013 23:27, schrieb skienzl:

**Comment by skienzl** [comment]
is verständlich

**Comment by skienzl** [comment]
sag bescheid wenn ich testen kann.

**Comment by Didi71** [comment]
sollte jetzt gehen.
