### ISSUE TITLE
CheckPoint - Info

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#170]
Wär's möglich die CheckPoint Info generisch aufzubauen?
## headline (headline_url)

body (=html text)

**Comment by skienzl** [comment]
wäre schon möglich das du einfach html quellcode gibst den ich dann ausgebe.

**Comment by Didi71** [comment]
des wär supa, dann wären wir superflexibel

Am 29.10.2013 23:08, schrieb skienzl:

**Comment by skienzl** [comment]
also es geht da einfach um das infofeld wenn ich auf den marker klicke oder?

**Comment by Didi71** [comment]
ja.

da sollte es eine headline geben, die könnte auch ein Link sein.
und darunter gibt's dann optional ein html-feld.
wenn es ein html feld gibt, dann sollten headline und html-feld durch 
einen horizontalen strich getrennt sein.

Am 29.10.2013 23:11, schrieb skienzl:

**Comment by skienzl** [comment]
alles klar. dann kommt ein cp also so zurück:

{
            "id": "bl2",
            "operation": "update",
            "header": "bikebird innovations",
            "header_url":"url",
            "body": "<p>sdfsadfsd</p>",
            "latitude": 47.226361145297,
            "longitude": 15.920342922211,
            "marker": "markerLightgrey.png",
            "events": []
        },

**Comment by skienzl** [comment]
gib bescheid wenn das auch geht und ich testen kann

**Comment by skienzl** [comment]
für den "link-indikator": ist es ok wenn der angezeigt wird sobald ein "</a>" tag vorkommt?

**Comment by Didi71** [comment]
ja - ich schick header_url nur mit, wenn es auch einen link gibt.

Am 31.10.2013 07:11, schrieb skienzl:

**Comment by skienzl** [comment]
ahhh. der hat jetzt meine " < / a'>" tag nicht genommen. ich dachte wenn du sowieso alles in html schickst, kannst den link auch gleich einbauen. und sobald ein link tag vorkommt, kommt auch der indikator

**Comment by Didi71** [comment]
nimmt er html dann auch im header?
wenn dem so ist, dann verwend' ich bei einem Link im Header auch das <a> 
tag.

Am 31.10.2013 07:14, schrieb skienzl:

**Comment by Didi71** [comment]
dann können wir auf die Sonderbehandlung mit ">" verzichten.

Am 31.10.2013 07:14, schrieb skienzl:

**Comment by skienzl** [comment]
ich habs einmal eingebaut das er html nimmt. muss noch testen :)

**Comment by Didi71** [comment]
ich zieh' grad was am Server gerade - könnte ca. 15 Minuten dauern bis 
alles Skripts wieder funktionieren.

Am 31.10.2013 07:18, schrieb skienzl:

**Comment by Didi71** [comment]
brauchst du die anderen Parameter wie name, webpage, etc. noch,
wenn nicht, dann nehm' ich's jetzt raus.

Am 31.10.2013 07:18, schrieb skienzl:

**Comment by skienzl** [comment]
kannst raus nehmen :)
