### ISSUE TITLE
getFactsV2-Test-Copy.php - Absturz, wenn TableCircle2Row als Subscreen

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#172]
Wenn ich als Subscreen einen TableCircle2Row zurückgeb, dann stürzt die App ab.
ich schick' dir gleich ein Testfile.

**Comment by skienzl** [comment]
habs jetzt behoben. aber bei mir waren keine table-screens eingetragen bei den "subscreens". also nicht vorgesehen.
