### ISSUE TITLE
getFactsV2.php -> Einem Team beitreten

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#173]
Wenn man noch keinem Team beigetreten ist, dann wird unter Facts der Screen: "TeamSelect" angezeigt. Für diesen Screen wird vom Server eine Headline geliefert, die aber nicht angezeigt wird. Es wird immer "Einem Team beitreten" angezeigt.

**Comment by skienzl** [comment]
yep. aber was willst du da auch sonst anzeigen?

**Comment by Didi71** [comment]
Da zeig ich "Teamwertung" an.
Ich hab's jetzt ein bissl umstrukturiert - auch um die Datentransfers 
klein zu halten - Musst mal gucken!

Am 31.10.2013 12:33, schrieb skienzl:

**Comment by skienzl** [comment]
kommt jetzt bei TeamSelect eine headline mit oder nicht?

**Comment by Didi71** [comment]
da war noch ein Tippfehler - jetzt schon

Am 02.11.2013 15:34, schrieb skienzl:
