### ISSUE TITLE
CheckPoint Info - Breite Trennlinie

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#176]
Die Trennlinie zwischen dem Header und dem Body ist maximal so breit wie der Header. Wenn der Body breiter ist als der Header schaut des net guad aus.

**Comment by Didi71** [comment]
ist noch immer so

**Comment by skienzl** [comment]
sicher? bei mir ist alles header breit

**Comment by Didi71** [comment]
Ja, aber die Linie sollte so breit sein wie das Fenster

Am 03.11.2013 um 16:52 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
"Die Trennlinie zwischen dem Header und dem Body ist maximal so breit wie der Header." ?? wie jetzt??

**Comment by Didi71** [comment]
Ich meinte, dass sie derzeit nur so breit ist wie der Header, aber so breit wie das Fenster sein sollte.

Am 03.11.2013 um 17:01 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
jetzt ist die Trennlinie so breit wie der Body. Wenn der header jedoch breiter ist, dann sollte sie so breit sein wie der Header.

![screen07](https://f.cloud.github.com/assets/5090129/1461929/b7a65c4e-44d7-11e3-9793-aa17cf814206.jpg)
