### ISSUE TITLE
CheckPoint Info - Links

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#177]
z.B. bei Kaufhaus Scheiblhofer (Kaindorf)

Die Links im body werden zwar angezeigt, aber man kann nicht draufdrücken.

Wenn der Header ein Link ist, dann sollte er auch unterstrichen dargestellt werden.

Macht das ">" Zeichen Sinn, oder können wir es uns sparen?

**Comment by skienzl** [comment]
das mit den links ist ein problem. da wird es nicht zugelassen das man den text anklicken kann. nur das ganze fenster bekommt den focus. was ich mir jetzt überlegt habe ist, dass du mir vl ein array mit links mitschickst. und wenn man dann auf das infowindow klickt kommt entweder eine liste mit den link anzeigenamen oder wenn es nur 1 link ist, gleich die seite. 
hab mir die response ca so vorgestellt: 

{
            "id": "cp13432023",
            "operation": "update",
            "latitude": 47.225277,
            "longitude": 15.910177,
            "marker": "markerRed.png",
            "header": "Kaufhaus Scheiblhofer",
            "body": "test test test"
            "links": [
                        {"name":"Scheiblhofers Betriebsradeln!", "link":"http://irgendwas.at"},
                        {"name":"Scheiblhofers Betriebsradeln!", "link":"http://irgendwas.at"}
                        ]
        }

**Comment by Didi71** [comment]
Passt! Mach ich heute Nacht.

Am 02.11.2013 um 17:32 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
d.h dann auch, dass die header_url nicht mehr nötig ist, oder?
Die Anzeige ob Links vorhanden sind erfolgt dann aber nach wie vor durch das ">", oder?

Am 02.11.2013 17:32, schrieb skienzl:

**Comment by skienzl** [comment]
genau. header_url brauch ich dann auch nicht mehr. und mit dem ">" wird angezeigt ob es einen link gibt
