### ISSUE TITLE
Die Punkte zum Wechseln zwischen Screens

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#178]
Wenn mehrere Screens angezeigt werden, dann erscheinen unten Kreise die anzeigen auf welchem Screen man sich gerade befindet.

Wird beispielsweise gerade ein Table3Row Screen angezeigt, und sind viele Zeilen anzuzeigen, dann überlagert die letze Zeile unten die Kreise.

Besser wäre, wenn sich Zeilen und Kreise nicht überlagern.

**Comment by skienzl** [comment]
hast heist du willst den table mit padding nach unten?

**Comment by Didi71** [comment]
wenn du bei der Demo in Gallneukirchen bereits mehr als 4 Preise 
gewonnen hast und die danach die Preisliste unter BIKEbirds anschaust, 
dann siehst du, dass sich die Tabelle und die Kreise überlappen - das 
sollte nicht so sein!
Am 02.11.2013 15:36, schrieb skienzl:

**Comment by Didi71** [comment]
Matthias hat vorgeschlagen die Kreise kleiner zu machen, so wie am IOS Home Screen. Dann würde auch nicht soviel Platz "verschwendet".

**Comment by Didi71** [comment]
ist zumindest am Galaxy Nexus noch immer so, dass sich Table und Kreise überlagern

**Comment by skienzl** [comment]
da brauch ich dann tables mit mehr einträgen bitte.

**Comment by Didi71** [comment]
Check doch bitte in Gallneukirchen ein, Gewinne Preise und Schau dir dann die Facts an.

Am 03.11.2013 um 16:54 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
also bei mir is alles fein. 0.0 überlappung.

**Comment by Didi71** [comment]
Dann ist's möglicherweise wieder ein Nexus Problem. Da hab's ja früher auch das Weiße-Listen Problem. Ich werd's mit dem Galaxy testen, sobald die App. Am Galaxy wieder funkt.

Am 03.11.2013 um 17:10 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
Ist leider noch immer so!

![screen05](https://f.cloud.github.com/assets/5090129/1461918/162d9a58-44d7-11e3-8472-b654b04bd090.jpg)

**Comment by skienzl** [comment]
bei der nächsten version bitte wieder überprüfen
