### ISSUE TITLE
Alle Circle-Screens

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#179]
Die derzeitige Formatierung der Circle-Screens ist suboptimal und schaut ned wirklich gut aus. Könntest du das bitte folgendemaßen ändern:

Die Kreise sollten immer mittig dargestellt werden. Wenn drei Kreise darzustellen sind, dann sollte die Mitte der drei Kreise genommen werden.

Oben gibt's den titel_1, der mittig zwischen dem oberen Rand und den Kreisen dargestellt wird. titel_1 kann auch mehrzeilig sein.

Unten gibt's den titel_2, der mittig zwischen den Kreisen und dem unteren Rand bzw. den unteren Screen-kreisen dargestellt wird. titel_2 kann auch mehrzeilig sein.

![allcircleinfo](https://f.cloud.github.com/assets/5090129/1456665/01f5fcd0-4331-11e3-8eb4-bba9eaaf246c.jpg)

**Comment by skienzl** [comment]
bis ich das bei allen screens angepasst habe brauche ich minimum 1std. sind 40€ ok?

**Comment by Didi71** [comment]
mach' ma €20! Ist ja auch für einen wohltätigen Zweck. ok?

Am 02.11.2013 15:38, schrieb skienzl:

**Comment by skienzl** [comment]
sicher is es für einen wohltätige zweck. sonst würde ich es auch nicht so billig machen. 
aber langsam sollte die app einmal eine finale version erhalten. 
weil ich muss ja auch noch andere sachen machen und auch von was leben. 
ich denke nicht das ich dich da übers ohr hau. mach ma diesmal noch 20 € und passt.

**Comment by skienzl** [comment]
kannst du für die ganzen circle screens bsp machen. damit ich testen kann. bitte einmal bei den hauptscreen(die mit den tabs) und einmal bei den unterscreen.

**Comment by Didi71** [comment]
kann ich da beim Text eigentlich auch htlm code eingeben oder nur reinen 
Text?

Am 02.11.2013 16:19, schrieb skienzl:

**Comment by skienzl** [comment]
ist nur mit rein text gelöst.

**Comment by Didi71** [comment]
brauchst du das noch?

Am 02.11.2013 16:19, schrieb skienzl:
