### ISSUE TITLE
checkInV2.php - lat, lng

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#180]
Bitte beim Aufruf von checkInV2.php die aktuellen Koordiation mitschicken, damit ich überprüfen kann, ob man sich beim Einchecken aus in der Nähe des CheckPoints befunden hat.

**Comment by skienzl** [comment]
kann ich schon machen. aber ich kann nicht immer garantieren das es die richtigen daten sind. weil ich da ja nur schnell die letzte bekannte position mitschicke. kann also auch falsch sein.

**Comment by Didi71** [comment]
wie lange dauert es denn, bis man die aktuelle Position bestimmt hat? 
Ein paar Sekunden oder? Kann es vorkommen, dass die aktuelle Position 
gar nicht bestimmbar ist?

Am 02.11.2013 12:31, schrieb skienzl:

**Comment by skienzl** [comment]
kommt drauf an. paar sekunden bis minuten. und der user kann natürlich auch immer verweigern.

**Comment by Didi71** [comment]
verweigern gilt nicht! der User muss aber denk ich eh' schon beim 
Installieren akzeptieren, dass seine aktuelle Position ermittelt werden 
kann.

aber minuten haben wir nicht zeit - solange wird niemand auf's 
einchecken warten.
Könntest du mir neben der lat und lng mitschicken von wann die 
Bestimmung stammt? Dann könnte ich im Hintergrund zumindest eine 
Watch-List führen.

Am 02.11.2013 12:33, schrieb skienzl:

**Comment by skienzl** [comment]
sicher geht verweigern. einstellungen --> standortzugriff --> häcken bei gps und standort per WLAN & Mobilfunknetz entfernen. 

kann leider auch nicht bestimmen von wann die gps pos kommt. das gibt der manager nicht her.

**Comment by Didi71** [comment]
ok!

Dann sagen wir dem User, dass die App beim Einchecken die Position 
bestimmen können muss (verweigern gilt nicht!), dann warten wir ein z.B. 
max. 5 Sekunden und hoffen, dass die Position bestimmbar ist. Wenn die 
Position innerhalb der 5 Sekunden bestimmt werden konnte, wird sie 
mitgeschickt, und wenn nicht, dann eben nicht.

Am 02.11.2013 12:39, schrieb skienzl:

**Comment by skienzl** [comment]
ok. wird gemacht. aber ich denke das ich da wieder eine halbe stunde brauche. also sagen wir 20€ mehr. ist das ok für dich?

**Comment by Didi71** [comment]
ok

Am 02.11.2013 12:48, schrieb skienzl:

**Comment by skienzl** [comment]
ist jetzt implementiert. obwohl das mit den 5 sec warten schon lange ist wenn man eincheckt. da könnten user schon ungeduldig werden wenn dann der request vl auch noch 3-4 sec dauert.

**Comment by Didi71** [comment]
Kannst du die Standortermittlung bitte starten, sobald der User die App. Aktiviert. Bis er dann auf Checkin geklickt und den Qr-Code anvisiert hat Vergehen bestimmt 5s.

Am 02.11.2013 um 15:09 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
Das ist auch für die Map besser 

Am 02.11.2013 um 15:09 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
dann muss ich das aber in einem service umstellen der im hintergrund zur app läuft. denn sonst sucht er nur wenn der hauptscreen sichtbar ist.

**Comment by skienzl** [comment]
willst du die last know location haben auch wenn die vl falsch ist? oder wenn man nur die hat lieber keine senden?

**Comment by Didi71** [comment]
schick mir auch bitte die last known, aber dann über einen zusätzl. 
Parameter [latLngUptoDate]=0.
ansonsten ist [latLngUptoDate] = 1.

Am 02.11.2013 16:49, schrieb skienzl:
