### ISSUE TITLE
Table2Row, Table3Row als Subscreens

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#184]
Table2Row und Table3Row werden als Subscreens nicht angezeigt.

bei
TableCircle2Row funktionierts.

Grundsätzlich sollten alle Screen-Typen auch als Subscreens angezeigt werden können.

**Comment by skienzl** [comment]
wo finde ich da beispiele?

**Comment by Didi71** [comment]
Da muss ich noch was basteln, kannst du für's erste nicht eine Table3Row als nehmen und als Table2Row testweise darstellen. Bin nämlich noch unterwegs und erst ab ca. 21 Uhr am PCs

Am 03.11.2013 um 17:05 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
dann wart ich lieber bis ich echte testdaten habe ;)

**Comment by Didi71** [comment]
versuch mal: getFactsV2-Test-Copy3.php

Am 03.11.2013 17:14, schrieb skienzl:

**Comment by skienzl** [comment]
schaut gut aus. nur "toast" und "Message" weis i noch nit wann das angezeigt werden soll

**Comment by Didi71** [comment]
Toast und Message werden immer vor allen anderen Screens der selben 
"Ebene" angezeigt.
Beide sollen auch nur einmal angezeigt werden.

Soll ich die Screenliste noch umsortieren, sodass Toast und Message 
jeweils gleich zu Beginn der Screenliste stehen?

Am 03.11.2013 21:02, schrieb skienzl:

**Comment by Didi71** [comment]
hab's jetzt umsortiert, sodass Toast und Message immer gleich zu Beginn 
stehen.

Am 03.11.2013 21:02, schrieb skienzl:

**Comment by skienzl** [comment]
besser vor dem array mit timstamp usw. au
bei welchen screens kann das überall kommen?

**Comment by skienzl** [comment]
weil das hamma eigentlich nur bei map und checkIn gesagt oder? maximal noch bei den facts. obwohl ich mir nicht denke das du es da jemals brauchen wirst? oder auf was willst du den user da so aufmerksam machen?

**Comment by Didi71** [comment]
ja, bei diesen drei Skripten könnte in der Antwort ein Toast oder eine 
Message kommen.
Sollen wir Toast und Message als Screen zurückliefern, oder eher als 
eigene Parameter?

Ich bin mittlerweile fast eher dafür sie als Parameter zurückzugeben.

Am 03.11.2013 21:09, schrieb skienzl:

**Comment by skienzl** [comment]
jetzt hast sie aber in den subscreens drin! 

und ich hab ja gemeint als parameter und nicht als screen. das pfuscht mir nämlich total rein :D 
ich werd die auch nicht speichern. weil die sollen den user doch nur einmal informieren.

**Comment by Didi71** [comment]
schau mal bitte im Wiki bei getCheckPointsV2.php, ob das Sinn macht.

Am 03.11.2013 21:09, schrieb skienzl:

**Comment by skienzl** [comment]
ich denke ein array ist zu viel oder?  mehr als 1 toast oder message würd den user denke ich nur nerven.  sonst wärs ok. 

Am 03.11.2013 um 21:23 schrieb Didi71 notifications@github.com:

> schau mal bitte im Wiki bei getCheckPointsV2.php, ob das Sinn macht.
> 
> Am 03.11.2013 21:09, schrieb skienzl:
> 
> > weil das hamma eigentlich nur bei map und checkIn gesagt oder? maximal 
> > noch bei den facts. obwohl ich mir nicht denke das du es da jemals 
> > brauchen wirst? oder auf was willst du den user da so aufmerksam machen?
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/Didi71/BIKELine-Android/issues/184#issuecomment-27652868.
> > 
> > —
> > Reply to this email directly or view it on GitHub.

Stefan Kienzl
http://skienzl.com/

**Comment by Didi71** [comment]
ja denk' ich auch. Dann mach' ma's so wie  unter getCheckPointsV2.php 
definiert.
Ich werd' gleich mal auch ins Wiki von getFactsV2.php und checkInV2.php 
kopieren und ein Testskript basteln.

Am 03.11.2013 21:25, schrieb skienzl:

**Comment by Didi71** [comment]
getFactsV2-Test-Copy3.php liefert jetzt einen toast und eine message

Am 03.11.2013 21:25, schrieb skienzl:

**Comment by skienzl** [comment]
geht ja :) 
soll ich dann wieder auf getFactsV2.php umstellen? 
werd jetzt nämlich die neue apk auf testflight laden.

**Comment by Didi71** [comment]
Ja

Am 03.11.2013 um 21:44 schrieb skienzl notifications@github.com:
