### ISSUE TITLE
HTML-Text

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#186]
Wir sind auf der Zielgeraden - du wirst dich also schon bald wieder mit anderen Dingen beschäftigen können 8-).

Eine (vorläufig) letzte Feature-Bitte hätte ich noch. 

Bei den Screens (OneOneCircleInfo, TwoCircleInfo, IconMessage, QuestionAnd3Answer, etc.) kann derzeit nur reiner Text angegeben werden.

Schöner wäre wenn man HTML Text angeben könnte, der zumindest <b>, <i>, <u>, <big>, <small>, <sub>, <sup> etc. unterstützt.

Basistextgröße sollte die aktuelle Textgröße sein.

Könntest du bitte den Aufwand und die Kosten abschätzen?

**Comment by skienzl** [comment]
meinst du jetzt immer für title1 und title2?

**Comment by Didi71** [comment]
Ja

Am 03.11.2013 um 18:05 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
da ich da schon was vorbreitet hab für die links zum anzeigen und ich da nicht viel ändern muss, mach i dir das gratis ;)

**Comment by Didi71** [comment]
juchee - danke!

Am 03.11.2013 18:45, schrieb skienzl:
