### ISSUE TITLE
CheckPoint - Infobreite wenn Link

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#189]
Auch wenn ein Link gegeben ist, sollte ein Infofenster nur so breit sein wie nötig und NICHT die gesamte Bildschirmbreite abdecken.

![screen06](https://f.cloud.github.com/assets/5090129/1461922/508674ea-44d7-11e3-8d76-c7694b7df5c3.jpg)

**Comment by skienzl** [comment]
hab derzeit noch keine lösung dafür gefunden. weis nicht ob ich das hinkriege.
