### ISSUE TITLE
Aktivierung - Automatik

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#19]
Wenn ein der PIN eingegeben wurden, dann soll nicht automatisch die Aktivierung erfolgen. Der User sollte auf den Button "Jetzt Aktivieren" drücken müssen.

Es dauert dann ein bisschen bis der Screen "Team bearbeiten" erscheint, wahrscheinlich weil das Laden der Bundesländer ein bisschen dauert. Da sollte beim Übergang zwischen Aktivierung + Anzeige des "Team bearbeiten" Screens eine Infobox mit "Lade BIKEline-Bundesländer ..." angezeigt werden.

Wenn Orgs geladen werden sollte "Lade BIKEline-Schulen ..." angezeigt werden.
Wenn Biker geladen werden sollte "Lade BIKEliner ..." angezeigt werden.

**Comment by skienzl** [comment]
Warum nicht automatisch anmelden? Ist doch viel angenehme für den User.

**Comment by Didi71** [comment]
Vielleicht bin ich ja schon zu alt für dieses neumoderne Technikzeug - ich fülle gern meine Formulare aus, schau dann nochmal drüber und bestätige dann explizit mittels Tastendruck.

**Comment by clueckler** [comment]
Würde dies auch extra mit Tastendruck machen, da der PIN in seiner Länge variiert und wir bei der Live-Version den PIN in keinem Request mehr mitbekommen. Also kann das nur durch Tastendruck realisiert werden!

**Comment by skienzl** [comment]
warum soll das nur durch tastendruck realisiert werden können? ich fang ja den "enter" bzw "done" key ab und das is das komplett gleich zum button

**Comment by clueckler** [comment]
Mein Fehler ... Automatisch heißt für mich:

> if (PIN.length == pinTextField.length) {
>  goAhead;
> }

Aber mit Enter / Done ist es auch logisch! =)

**Comment by starflower** [comment]
Wenn der Enterkey nicht aktiviert sein soll, **MUSS** der "Jetzt aktivieren"-Button über dem Keyboard sein. Keyboard Ausklappen und dann Button drücken ist **sehr schlechte** UX

**Comment by Didi71** [comment]
Echt!   Also ich hätte mir gedacht, dass ich die PIN eingeb (Keyboard sichtbar), dann auf "OK" drücke, daraufhin das Keyboard verschwindet und ich danach auf "Jetzt Aktivieren" drücke.
