### ISSUE TITLE
CheckPoint - Infoscreen - langer Header

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#192]
Wenn der Header des Infoscreens länger als die Bildschirmbreite ist, dann wird zwar umgebrochen, aber der Trennstrich falsch angezeigt.

![screen10](https://f.cloud.github.com/assets/5090129/1467885/dec3bc10-4589-11e3-85e0-7c6636deded2.jpg)

**Comment by skienzl** [comment]
bitte wieder testen
