### ISSUE TITLE
CheckPoint - Öffne Webpage

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#193]
bitte die Links, linksbündig anzeigen

Am Samsung Galaxy kann man auf den Hintergrund tippen, und das Auswahlfenster verschwindet.

Am Nexus geht das nicht, und man muss auf den Back-Button drücken und die Auswahl abzubrechen - das ist umständlich - bitte korrigieren

**Comment by skienzl** [comment]
bitte wieder bei der nächsten apk testen
