### ISSUE TITLE
Registrierung

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#194]
Bei der Registierung hängt die App. und zeigt immer PIN-Überprüfung an.

**Comment by skienzl** [comment]
ich bekomme diese antwort vom server: 
Invalid address: {"errorCode":0,"bikerId":11,"bikerFirstName":""} 

![bildschirmfoto 2013-11-04 um 22 32 38](https://f.cloud.github.com/assets/4992387/1468805/a91f1834-4598-11e3-9452-6944e5a9fad3.png)

**Comment by skienzl** [comment]
das Invalid address gehört da denke ich nicht hin

**Comment by Didi71** [comment]
ich versteh's nicht ganz - woher kommt denn die street und der postal code.
die Felder gibt's doch gar nicht mehr beim Registrieren.

Am 04.11.2013 22:33, schrieb skienzl:

**Comment by skienzl** [comment]
ich wollts nur noch einmal probieren wie es in der doku ist. aber das "Invalid address" kommt sowieso immer

**Comment by Didi71** [comment]
hab's jetzt korrigiert - ich hatte noch Parameter übernommen die gar 
nicht mehr mitgeschickt werden.
jetzt sollte es gehen - bei mir zumindest tuts.

greifst du bei der neuen APK auf App-Skripts oder TestApp-Skripts zu?

Am 04.11.2013 22:47, schrieb skienzl:

**Comment by skienzl** [comment]
noch immer auf TestApp-Scripts.

**Comment by Didi71** [comment]
passt - lass ma für's erste so.

Am 04.11.2013 22:52, schrieb skienzl:
