### ISSUE TITLE
Questions - sehr lange

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#196]
Wenn die Frage und die Antworten zu lang sind, dann sollte man die Antworten scrollen können (siehe roter Balken)

Die Frage und die Antwortmöglichkeiten (A, B, C) sollten immer oben bzw. unten sein.

![screen13](https://f.cloud.github.com/assets/5090129/1476412/b5d70b84-4649-11e3-8487-3c0e1f59c00c.jpg)

**Comment by skienzl** [comment]
mach den text bitte noch länger damit ich testen kann.

**Comment by Didi71** [comment]
here you go.

Am 05.11.2013 19:45, schrieb skienzl:
