### ISSUE TITLE
Question A, B, C

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#197]
Links neben den Antwortmöglichkeiten sollte jeweils A) B) und C) in normaler Schriftgröße stehen.

Die Schriftgrößen und das Format sollten gleich wie bei allen anderen Screens sein

![screen14](https://f.cloud.github.com/assets/5090129/1476473/84c768c6-464a-11e3-9a4a-9a7f04b7611d.jpg)

**Comment by skienzl** [comment]
kannst du das nicht mitschicken? a? b? c?

**Comment by Didi71** [comment]
wenn ich's mitschicke, dann passt die Ausrichtung nicht

Am 05.11.2013 19:49, schrieb skienzl:
