### ISSUE TITLE
QuestionAnd3Answer - Screen

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#198]
1.) Der Abstand zwischen dem Rand und der Frage sollte so groß sein wie der Abstand zwischen Frage und Antwort A

2.) Wenn eine Frage nicht beantwortet werden kann, dann soll ein Toast mit folgendem Text angezeigt werden.

"Deine Antwort ist leider falsch. In X Sekunden stelle ich dir die nächste Frage."

wobei X runterzählen soll von "questionDelayIsS" bis 0, bei Null wird die nächste Frage gestellt.

Falls das Runterzählen durch ""BACK" unterbrochen wird, soll der Countdown im Hintergrund weiterlaufen. Wenn das Runterzählen durch "HOME" unterbrochen bzw. die App. gestoppt wird, soll der Countdown weiterlaufen sobald die App. wieder gestartet wurde.

Wenn danach wieder CheckIn gewählt wird und der Countdown noch nicht abgelaufen ist, sollte folgender Toast angezeigt werden.

"Der nächste CheckIn ist in X Sekunden möglich".

3.) Wenn das Stellen der Fragen unterbrochen wird (z.B. durch HOME oder BACK), dann sollte beim nächsten CheckIn NICHT nocheinmal die Frage gestellt werden, sondern nochmal eingecheckt werde.

**Comment by skienzl** [comment]
was meinst du mit back unterbrochen wird? wenn er back drückt schließt der screen und er ist wieder am main screen? das heist der screen wird gelöscht.  
und glaubst du nicht das das mit den ganzen "Der nächste CheckIn ist in X Sekunden möglich" zu umständlich ist? machen wir doch so wie schon am telefon besprochen. wenn die app stoppt (home button)  = ganz normal am main screen.

**Comment by Didi71** [comment]
das problem ist dann nur, dass der user den countdown umgehen kann, 
indem er die App beendet und danach gleich wieder startet.

Am 06.11.2013 21:13, schrieb skienzl:

**Comment by Didi71** [comment]
aber - lass ma's amal so wie besprochen.

wenn die user so schlau sind die app zu unterbrechen und danach gleich 
wieder zu starten, haben sie es sich verdient.
mach ma's so wie telefonisch besprochen.

Am 06.11.2013 21:13, schrieb skienzl:

**Comment by skienzl** [comment]
dann is er e wieder am main screen. da vergehen min 5 sec. oder wie lange willst den countdown machen. is halt dann alles aufwendiger um komplizierter mit der umsetztung des ganzen wenn nach dem start wieder ein countdown kommen soll.

**Comment by Didi71** [comment]
Die neue APK tut's aber immer noch nicht.

![screen16](https://f.cloud.github.com/assets/5090129/1502646/dac148aa-489d-11e3-9205-181111f5a533.jpg)

**Comment by Didi71** [comment]
Die Headline klebt leider immer noch ganz oben - bitte oben das doppelte padding
