### ISSUE TITLE
sounds

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#199]
Liegt's an meinen Handies, oder werden keine Sounds mehr abgespielt?

**Comment by skienzl** [comment]
is bei alle. 

aber der grund is das wenn man bei getResourceV2.php einen sound abruft kommt das:

<br />
<b>Notice</b>:  Undefined index: resolution in 
<b>/home/.sites/228/site1541/web/BIKElineCheckPoint/TestApp-Scripts/getResourceV2.php</b> on line 
<b>25</b>
<br />
{"errorCode":0,"data":"\/\/tgxAAAA9QBa7QAACMpMWw\/MvIAAAIAHo4A3+Hl\/6i5\/l\/\/.....

**Comment by Didi71** [comment]
Herrschaftsseitn - bin i bled!
Geht jetzt!

Danke
Didi

Am 10.11.2013 18:02, schrieb skienzl:
