### ISSUE TITLE
Anmeldung + keinem Team beitreten

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#20]
Wenn man sich anmeldet und danach keinem Team beitritt, dann kommt man wieder zum Start-Screen mit Anmelden + Registrieren, obwohl die Anmeldung erfolgt ist.

**Comment by skienzl** [comment]
Schon gesehen und verbessert. Mein Fehler :)

**Comment by clueckler** [comment]
@skienzl wenn was ausbesserst tu bitte auch die Tickets closen, damit sich jeder auskennt ;-)
