### ISSUE TITLE
getGeneralInfo.php

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#200]
Wenn der Menüpunkt allgemeine Infos aufgerufen wird, dann soll der anzuzeigende Text vom Server geholt werden.

Wenn keine Internetverbindung verfügbar ist, dann sollte der zuletzt von Server geholte Text angezeigt werden. Wenn noch nie ein Text vom Server geholt wurde, dann soll ein Standardtext angezeigt werden.

**Comment by skienzl** [comment]
hab mir gerade getGeneralInfo.php angeschaut. das is ja wieder alles komplett generisch. ist das wirklich notwendig??? reicht dir da nicht der text? das ist doch nur ein info screen

**Comment by Didi71** [comment]
Ich dachte, dass du das Generische einfach von Getfacts übernehmen kannst und es somit nicht viel Aufwand ist. Wenn wir es als Screen machen, dann könnte ich es später auch bei Facts und Checkin verwenden.

Am 15.11.2013 um 16:28 schrieb skienzl notifications@github.com:
