### ISSUE TITLE
TeamSelect - zwingend erforderlich

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#202]
Bei der BIKEline-App (nicht bei CheckIn) ist es zwingend erforderlich, dass man einem Team beitritt, bevor man das erste Mal eingecheckt hat.

Ich gebe deshalb bei checkInV2-Test.php den Screen TeamSelect und einen Toast zurück, dass man vor dem ersten Einchecken einem Team beitreten muss.

TeamSelect wird derzeit noch nicht als Screen beim CheckIn akzeptiert.

**Comment by skienzl** [comment]
TeamSelect war dort auch nie vorgesehen. Das muss ich jetzt extra implementieren

**Comment by skienzl** [comment]
kannst du mir da ein example machen. damit ich das testen kann.

**Comment by Didi71** [comment]
versuch's mal mit checkInV2-Test2.php

Am 17.11.2013 19:55, schrieb skienzl:

**Comment by skienzl** [comment]
funkt. danke

**Comment by skienzl** [comment]
aber eigentlich hab ich e gespeichert ob der biker schon bei einem team ist. das könnte ich ja auch schon vor dem einchecken überprüfen? das wäre die bessere lösung oder?

**Comment by Didi71** [comment]
ja, das wär noch besser

Am 17.11.2013 20:53, schrieb skienzl:
