### ISSUE TITLE
api checkInV2-Test.php changed

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#203]
Wenn beim CheckIn ein QR-Code gelesen wird, dann sollte der QR-Code in der App nicht bewertet werden. Es sollte in der App lediglich geprüft werden, ob es sich bei dem QR-Code um einen Link handelt.

Danach wird checkInV2-Test.php aufgerufen und folgende Parameter übergeben (siehe checkInV2-Test.php)

URL: die URL des QR-Codes
params: key=checkPointId   value=13432020

damit lassen sich QR-Codes mit beliebigen URLs und Parametern erzeugen.

**Comment by skienzl** [comment]
lässt du jetzt alle QR codes neu machen?

**Comment by Didi71** [comment]
ja - muss ich leider, weil sich das Design durch die klare Trennung 
zwischen BIKEline und CheckIn auch ändert.
Zum Glück hat mein Bruder eine Druckerei.

Am 19.11.2013 17:23, schrieb skienzl:

**Comment by skienzl** [comment]
kannst du mir einmal so eine url schicken?

**Comment by Didi71** [comment]
here you go!

Am 19.11.2013 18:32, schrieb skienzl:

**Comment by skienzl** [comment]
also sind die keys jetzt "cp" und "rnd" ?

**Comment by Didi71** [comment]
ja!

cp ist die CheckPoint-Nummer und rnd ist eine Zufallszahl, damit man 
sich nicht einfach CheckPoints selbst zu Hause basteln kann.
Ist kein absoluter Schutz, aber eine kleine weitere Hürde.

Am 19.11.2013 19:27, schrieb skienzl:

**Comment by Didi71** [comment]
das mit den Parameter hatte ich anders gemeint.
params ist ein Array von key/value Paaren.

z.B.
params[0].key = "cp"
params[0].value = "13432020"
params[1].key = "rnd"
params[2].value = "36025640"

oder 

params["cp"] = "13432020";
params["rnd"] = "36025640"
