### ISSUE TITLE
registerBiker - loginBiker

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#204]
Nachdem 'CheckIn' nun toll flutscht, hab' ich BIKEline-CheckPoint ein wenig getestet.

Hab' versucht mich mit meinem Nexus zu registrieren. Sowohl bei "Bereits Mitglied" als auch bei "Registrieren" wechselt die App. nachdem die Server geantwortet hat aber nicht auf den Screen in dem die PIN eingegeben werden kann.

Hast du eine Ahnung woran es liegt - am Server seh' ich keine Probleme.

**Comment by skienzl** [comment]
hey. war über silvester nicht im lande. hab gerade alles gecheckt. hast du am server irgendwas geändert? dem app gefällt auf einmal der json string nicht mehr.

**Comment by Didi71** [comment]
Hi! Ich hab am Server zwar was bei den Datenbank umgestellt, aber der String sollte unverändert sein. 

Am 02.01.2014 um 20:13 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
kann es sein das du auch pages verändert hast: 

weil "/BIKElineCheckPoint/TestApp-Scripts/getCheckPointsV2.php" ist zb auch nicht aufrufbar.

**Comment by Didi71** [comment]
Nein die Pages sind gleich, aber auch bei getCheckpoints... Hab ich an der Datenbank gebastelt. Was ist , wenn du die Skripts am Browser aufrufst? Bei mir schaut's nämlich gut aus.

Am 03.01.2014 um 12:30 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
kann er nicht finden

![bildschirmfoto 2014-01-03 um 13 41 25](https://f.cloud.github.com/assets/4992387/1839212/64a0b3f6-7474-11e3-8ef0-be0bcae9a4e0.png)

**Comment by Didi71** [comment]
Oha. Das kann sein, weil ich alle Skripts vom Server entfernt hab, um nach und nach nur die Dinge raufzuladen, die ich wirklich benötige. Hatte mit dem Registrieren begonnen, deshalb fehlt getCheck... noch. 

Bin derzeit leider nicht zu Haus, kann's erst später hochladen.

Am 03.01.2014 um 13:42 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
jetzt hab ich's raufgeladen - sorry sehr spät.

**Comment by Didi71** [comment]
das liefert z.B. 

http://www.bikebird.at/BIKElineCheckPoint/TestApp-Scripts/loginBiker.php?bikerEmailAddress=dietmar.scheiblhofer@bikebird.at

{"errorCode":0,"bikerId":1,"bikerFirstName":"Didi"}

**Comment by skienzl** [comment]
jetzt fehlt glaube ich noch "getFactsV2.php" oder?

**Comment by Didi71** [comment]
hab's jetzt auch hochgeladen, sollte aber keinen Einfluss auf unser Problem haben.

**Comment by skienzl** [comment]
das weis ich schon das es mit dem problem nichts zu tun hat :) hab das jetzt denke ich schon im griff. aber muss es halt überall testen :) 

hab gesehen das bei "getProvinces.php" noch die query zurück kommt.

**Comment by Didi71** [comment]
hab' getProvinces korrigiert.

Am 07.01.2014 08:45, schrieb skienzl:
