### ISSUE TITLE
checkIn - Nexus

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#208]
Am Nexus funktioniert das Einchecken nicht.
Am Screen wird noch das Infofenster (Checkin läuft ...) angezeigt, aber danach passiert nix 
![screen01](https://f.cloud.github.com/assets/5090129/1896283/3f22c6fe-7b91-11e3-9680-9cd18e3d6d02.jpg)

**Comment by skienzl** [comment]
ich hab da nur das problem das ich den fehler bei keinen meiner geräte hab und daher nicht feststellen kann woher der fehler kommt

**Comment by Didi71** [comment]
ich glaub es hängt auch gar nicht speziell am Nexus sondern an Android 
2.2 oder 2.3, weil ich den Effekt auf meinen älteren Tablets auch hab.

Am 14.01.2014 17:28, schrieb skienzl:

**Comment by skienzl** [comment]
das problem ist nur das ich niemanden kenne der ein gerät unter 2.3.3 hat. sind ja auch nur mehr 1% aller geräte die unter 2.3.3 sind.

**Comment by Didi71** [comment]
hab's grad mit dem Handy meiner Tochter probiert (Sony: Xperia U - Android 2.3.7) - da geht's leider auch nicht.
Wenn du willst, dann kann ich dir testweise das Nexus schicken.

**Comment by skienzl** [comment]
kann es sein das du da noch den die daten eingebunden hast die uns die json probleme gemacht hat? 
hab nämlich jetzt ein gerät mit android 2.3.5 und da kommt wieder der fehler beim checkin

**Comment by Didi71** [comment]
den fehler beim checkin mit den android geräten hab ich auch.

aber die datei, die damals die probleme am server verursacht hat wird 
nicht mehr eingebunden.
beim checkin sollte deshalb serverseitig alles clean sein.

welchen fehler liefert dir denn dein android 2.3.4?

Am 16.01.2014 12:06, schrieb skienzl:

**Comment by skienzl** [comment]
den gleichen fehler wie bei den json problemen die wir hatten. er kann den string nicht parsen. auch das gleiche verhalten. das heist bei neuen geräten (android 4.x) gehts und bei älteren android versionen nicht.

**Comment by Didi71** [comment]
komisch ist nur, dass der String (zumindest im Browser) exakt gleich 
ausschaut.
Kann's sein, dass der Zeichensatz ein anderer ist, und deshalb das alte 
Android Probleme macht?

Am 16.01.2014 13:03, schrieb skienzl:

**Comment by skienzl** [comment]
seh auf den ersten blick keinen unterschied bei den zeichensätzen bzw auch kein unterschied in den ganzen http headern.

**Comment by Didi71** [comment]
schräg oder?

Am 16.01.2014 13:06, schrieb skienzl:

**Comment by skienzl** [comment]
ich parse das ja jetzt schon mit 2 verschiedenen arten um sicher zu gehen und es funktionieren beide nicht.

**Comment by skienzl** [comment]
ich habs jetzt bei mir zum laufen gebracht. da war iwas mit den string anfang oder ende falsch. wenn ich sag er soll erst bei erstn "{" anfangen und beim letzten "}" aufhören dann gehts. sehr komisch. ich hoffe es geht jetzt bei dir auch. bitte testen. lade gerade die apk auf testflight hoch
