### ISSUE TITLE
Höhe von Dialogfenstern: Samsung Galaxy S3

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#210]
Die Höhe von Dialogfenstern stimmt nicht. Unter den Buttons z.B. "Beitreten" und "Abbrechen" ist eine große schwarze Fläche.

**Comment by Didi71** [comment]
Es muss auch was mit der App zu tun haben, denn bei der CheckIn-App tritt der Fehler nicht auf, bei der BIKEline-App aber sehr wohl - Samsung Galaxy S3 mini

![screen02](https://f.cloud.github.com/assets/5090129/1964882/7d95b792-82b3-11e3-9327-36e1aa8d55a8.jpg)
![screen01](https://f.cloud.github.com/assets/5090129/1964883/7d98d47c-82b3-11e3-8032-f529ba48f614.jpg)

Am Nexus One schaut's korrect aus:
![screen05](https://f.cloud.github.com/assets/5090129/1965041/76769eca-82b5-11e3-9ff5-cdfdb8d1fafe.jpg)

**Comment by skienzl** [comment]
aber das haben wir schon einmal kapt mit den S3 oder? da is dann einscheinend ein fehler beim dark theme.

**Comment by Didi71** [comment]
Können wir dann das gleiche Themen nehmen wie bei der BIKEline ?

Am 21.01.2014 um 20:11 schrieb skienzl notifications@github.com:
