### ISSUE TITLE
Profil bearbeiten - Foto Aufnahme - Absturz

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#213]
Wenn man das Profil bearbeitet und ein Foto aufnimmt, dann stürzt die App hin und wieder ab. Getestet am S3 mini und Nexus. Generell steht die App. kurze Zeit nachdem man das Foto akzeptiert hat.

Die Überschrift beim Aufnehmen von Fotos sollte sein: Profilbild aufnehmen

**Comment by skienzl** [comment]
hab gerade am S3 mini viele tests gemacht und konnte aber nix feststellen. kein absturz

**Comment by Didi71** [comment]
Ist bei mir aber grad wieder abgestürzt. 
Suboptimal ist auch, dass wenn man ein Bild aufgenommen hat, und man dann auf den Haken oder das Kreuz drückt, keine Änderung sieht. Ich mein' der Haken oder das Kreuz sollten jeweils farblich hinterlegt sein, wenn man draufdrückt.

**Comment by Didi71** [comment]
du hattest mal einen Logger eingebaut, wo du die Abstürze dann auch gesehen hast - gibt's den noch?

**Comment by skienzl** [comment]
bitte wieder testen beim nächsten mal :)

**Comment by skienzl** [comment]
bitte auch wieder testen
