### ISSUE TITLE
Allgemeine Infos - Textgröße

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#214]
Die Textgröße bei den allgemeinene Infos (Screen: "Info") sollte gleich groß sein wie bei der CheckIn-App.

**Comment by skienzl** [comment]
die ist schon gleich. aber du hast den "small" tag gesetzt.

**Comment by Didi71** [comment]
komisch - ich hatte den Text 1:1 von der CheckIn-App übernommen, aber da 
wird das "small" größer dargestellt.

Am 21.01.2014 09:32, schrieb skienzl:

**Comment by skienzl** [comment]
aber das layout ist auch 1:1 zum CheckIn-App

**Comment by skienzl** [comment]
vl hast du den text in den test-script kopier aber nicht in den release scripts.

**Comment by Didi71** [comment]
nö - hab, jetzt grad' das getGeneralInfo.php von CheckIn -> BIKEline 
kopiert - BIKEline stellt den Text kleiner dar.
Da muss irgendwas im Screen unterschiedlich sein.

Am 21.01.2014 09:34, schrieb skienzl:

> vl hast du den text in den test-script kopier aber nicht in den 
> release scripts.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Didi71/BIKELine-Android/issues/214#issuecomment-32829442.

![screen04](https://f.cloud.github.com/assets/5090129/1964909/cb66fed6-82b3-11e3-8d27-5f5da42212d7.jpg)
![screen03](https://f.cloud.github.com/assets/5090129/1964910/cb69af64-82b3-11e3-970a-18bb3133dd46.jpg)

**Comment by Didi71** [comment]
beide Apps erhalten exact die gleichen Daten ... aber

![screen04](https://f.cloud.github.com/assets/5090129/1964917/e1772d4a-82b3-11e3-8342-be544205a51a.jpg)
![screen03](https://f.cloud.github.com/assets/5090129/1964918/e17a62ee-82b3-11e3-885c-3d6b0cb9b3f0.jpg)
