### ISSUE TITLE
Einem Team beitreten - Diverses

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#215]
Der Text: "Jeder BIKEbird den du ..." ist um ein Zeichen zu weit rechts.

Wenn man am Screen "Einem Team beitreten" im Actionbar auf "zurück" tippt, dann kommt man ja wieder zum Hauptscreen. Dabei wir der Bildschirm, anders als bei allen anderen Screens kurzzeitig schwarz. Gibt's einen bestimmten Grund, warum das zurück hier anders aussieht als bei allen anderen Screens?

**Comment by skienzl** [comment]
ich sehe da bei mir keinen unterschied wenn ich ehrlich bin. gleiches verhalten bei allen geräten.

**Comment by Didi71** [comment]
Interessant: wenn ich z.B. mir die Facts anschau und dann auf "zurück" tippe, dann faded der aktuelle Screen und der Hauptscreen erscheint.

wenn ich hingegen bei "Einem Team beitreten" auf "zurück" tippe, dann verschwindet der Screen nach oben und der Hintergrund ist dabei "schwarz". erst danach wird der Hauptscreen angezeigt. - Ist am Samsung Galaxy S3 Mini so.

Aber vergiss es - ich wollt's nur wissen.
