### ISSUE TITLE
Lade CheckPoints ... Nexus One

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#218]
Beim zweiten Aufruf der CheckPoint-Liste bleibt die App. stecken. (bei der CheckIn-App funktionierts)

![screen06](https://f.cloud.github.com/assets/5090129/1965066/d24597c4-82b5-11e3-818f-e215a1d213d3.jpg)

**Comment by skienzl** [comment]
dreht sich die progressbar dann auch nicht mehr?

**Comment by Didi71** [comment]
der dreht sich und dreht sich und ...

**Comment by skienzl** [comment]
bitte beim nächsten release auf testflight testen

**Comment by Didi71** [comment]
Nexus:
Mit der neuen Release ist das Verhalten anders.
Wenn man sich gerade erst angemeldet hat und getCheckPoints das erste Mal aufruft, dann steckt die App.
Wenn man die App. aber verlässt und danach nochmal startet funktioniert die Anzeige der CheckPoints (meistens)

Samsung Galaxy S3 Mini:
Wenn man sich gerade erst angemeldet hat und getCheckPoints das erste Mal aufruft, dann werden keine CheckPoints eingelesen bzw. angezeigt.
Wenn man die App. aber verlässt und danach nochmal startet funktioniert die Anzeige der CheckPoints (meistens)

**Comment by Didi71** [comment]
das Problem tritt nach wie vor auf, allerdings nicht nur beim Nexus, sondern auch beim Galaxy.
Jede 3. - 4. Mal steckt die App.

**Comment by skienzl** [comment]
anscheinend sendest du am ende immer ein leerzeichen mit das den ursprünglichen fehler hervorgerufen hat. das er den string nicht erkennt.

**Comment by Didi71** [comment]
Da hab ich aber nix geändert. Und ich wüsste auch nicht wo ich das Leerzeichen sende.

Am 23.01.2014 um 15:04 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
das problem mir dem laden besteht aber ca seit den letzten problemen mit json. und das leerzeichen ist am ende. habs auch auf der tcp protokoll ebene gecheckt (siehe screenshot). 

![leerzeichen](https://f.cloud.github.com/assets/4992387/1985369/06ab8bc6-843d-11e3-84bd-c71e9dad6fe6.png)

**Comment by skienzl** [comment]
ich werd das probieren selbst weg zu filter. also brauchst nichts umstellen

**Comment by skienzl** [comment]
ich hoffe es geht jetzt dann

**Comment by Didi71** [comment]
schaut gut aus, obwohl die Ladezeit jetzt sicherlich 3x so lang ist wie zuvor.
