### ISSUE TITLE
Homescreen - Logo

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#219]
Wäre es möglich, dass das Logo ca. 50% der Breite des HomeScreens einnimmt (wie beim Galaxy).

Bei größen Display (Odys Space) schaut's sonst nämlich uncool aus.

![screen20](https://f.cloud.github.com/assets/5090129/1965567/b6b7d606-82bb-11e3-8b22-93ae3952df73.jpg)

**Comment by skienzl** [comment]
tablet layout müsste ich extra erst machen.

Am 21.01.2014 um 17:47 schrieb Didi71 notifications@github.com:

> Wäre es möglich, dass das Logo ca. 50% der Breite des HomeScreens einnimmt (wie beim Galaxy).
> 
> Bei größen Display (Odys Space) schaut's sonst nämlich uncool aus.
> 
> —
> Reply to this email directly or view it on GitHub.

Stefan Kienzl
http://skienzl.com/

**Comment by Didi71** [comment]
kann man beim Layout nicht generell angeben, dass das Logo 50% der 
Breite einnimmt.
Das müsste doch gehen oder?

Am 21.01.2014 17:50, schrieb skienzl:
