### ISSUE TITLE
Focusfarbe im Hauptmenü (Nexus)

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#221]
Die Focusfarbe im Hauptmenü ist gelb - sollte aber türkis sein.

![screen23](https://f.cloud.github.com/assets/5090129/1968984/be7e9fd4-82eb-11e3-87d4-9b18b90c4952.jpg)

**Comment by Didi71** [comment]
jetzt ist bei Android 2.3 die Schriftfarbe weiß, wenn die Buttons keinen Fokus haben.
Die Focusfarbe ist nach wie vor gelb.

![screen33](https://f.cloud.github.com/assets/5090129/1988873/5ae9e5ee-846e-11e3-938c-04a8b7e82d9b.jpg)

**Comment by Didi71** [comment]
das ist jetzt aber das letzte Problem das ich noch gesehen hab ;-))

**Comment by skienzl** [comment]
ich wollte da was probieren. aber anscheinend wir die highlight farbe immer vom system überschrieben.

**Comment by skienzl** [comment]
die hightlight farbe wird echt immer von jedem system überschrieben. das wird nie ein einheitliches bild. leider. ich lass am besten die default sachen. sonst kommen wahrscheinlich nur mehr probleme

**Comment by Didi71** [comment]
ok!

Am 28.01.2014 09:46, schrieb skienzl:
