### ISSUE TITLE
Profilbild versehentlich aufnehmen (Nexus)

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#227]
Wenn man versehentlich auf das Bild im Profil tippt, dann erscheint dieses Infofenster.
Beim Galaxy kann man die Aufnahme abbrechen, indem man irgendwo auf den Screen tippt. Beim Nexus funktioniert das nicht!

![screen28](https://f.cloud.github.com/assets/5090129/1969080/563d351e-82ed-11e3-8d8d-df1eccfb68c7.jpg)

**Comment by skienzl** [comment]
auch hier wieder. das nexus unterstütz das anscheinend einfach nicht. ich muss leider aufhören für das nexus workarounds zu machen.

**Comment by Didi71** [comment]
Da geht's nicht ums Nexus, da geht's um Android 2.3

Am 22.01.2014 um 09:23 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
bitte wieder testen
