### ISSUE TITLE
Checkin-fehlgeschlagen (Nexus)

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#229]
Wenn am Galaxy der Checkin fehlschlägt als Hintergrund das aktuelle Bild. Beim Nexus ist der Hintergrund schwarz, was suboptimal ausschaut.

![screen30](https://f.cloud.github.com/assets/5090129/1969206/fa269fac-82ee-11e3-8c19-1314701b3752.jpg)
![screen32](https://f.cloud.github.com/assets/5090129/1969220/1e49fdd4-82ef-11e3-82fe-30f0365ccca0.jpg)

**Comment by skienzl** [comment]
sorry. aber ich kann fürs nexus nicht alles umbauen. das haut mir immer mehr alles zusammen.
