### ISSUE TITLE
Buttons - gedrückt - Darstellung

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#23]
Wenn Buttons gedrückt werden, dann wird das meistens auch grafisch dargestellt.
Ist das deaktiviert?

**Comment by skienzl** [comment]
bei allen buttons? siehst du eine veränderung bei den buttons am hauptscreen? also "checkIn" "map" usw?

**Comment by Didi71** [comment]
am hauptscreen seh ich keine veränderung

**Comment by starflower** [comment]
Funktioniert bei mir jetzt App#7 (HTC Desire S, Android 4.0.4, HTC Sense 3.6)

**Comment by Didi71** [comment]
bei mir auch
