### ISSUE TITLE
bikebirds - Lade BIKEline-Bundesländer

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#231]
Wenn man noch in keinem Team ist und sich die Bikebirds anzeigen lässt, dann erscheinen zwei Infoboxen: 1. Lade BIKEbirds ... und 2. Lade BIKEline-Bundesländer ...
Wozu die 2-te Box?

**Comment by skienzl** [comment]
weil er immer den screen der neben dem aktuellen ist schon vorläd. damit das wechseln schneller geht. und wenn man noch keinem team beigetreten ist, dann ist das eben der "team betreten screen" und der läd die bundesländer.

**Comment by Didi71** [comment]
ok - verstanden - passt.

Am 23.01.2014 09:16, schrieb skienzl:
