### ISSUE TITLE
Team beitreten -> Lade Bundesländer

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#233]
irgendwas ist da ziemlich instabil - wenn ich einem Team beitreten will, dann bleibt die App. bei "Lade Bundesländer ..." hin und wieder hängen.

Kann das irgendwas mit einem Timeout zu tun haben. Mir ist vorgekommen, dass die App., seit auch die Anzeige der CheckPoints fehlerfrei funktioniert länger dauert.

Hast du da eine Warteschleife eingebaut?

![screen35](https://f.cloud.github.com/assets/5090129/1988896/db3b9dc8-846e-11e3-802e-b398608995a4.jpg)

**Comment by Didi71** [comment]
die App. bleibt sporadisch hängen, wenn man noch nie einem Team beigetreten war. Sobald man einmal ein Team gewählt hat funktioniert's.

**Comment by skienzl** [comment]
aber das is doch alles komisch. warum sollen auf einmal alle die server kommunikations sachen probleme machen wo nie probleme waren. das kann ich nicht verstehen.
