### ISSUE TITLE
Facts / Team - Gesamtpunkte

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#28]
Toll wäre, wenn ganz oben beim Team in einem Kreis die Gesamt-BIKEbirds-Zahl des Teams angezeigt würde

**Comment by skienzl** [comment]
wenn du im "getTeamCheckIns.php" die Gesamt-BIKEbirds-Zahl zurück gibst dann kann ich das sicher einbauen :)

**Comment by Didi71** [comment]
getTeamCheckIns.php liefert nun einen zusätzlichen Parameter: "teamBikebirds"

**Comment by starflower** [comment]
Ich würd hier keinen Kreis machen, da der hier nur zentriert ausgerichtet über dem Namen zur Geltung kommen würde, das aber viel zu viel Platz einnimmt, wenn es fixiert unter der Tabbar ist. Viel eher würd ich einen String nach dem Ort anhängen zB "aus Kalsdorf – 130 BIKEbirds"

**Comment by Didi71** [comment]
Jo - das mach ma so.
