### ISSUE TITLE
Preise ansehen

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#3]
Wenn ein BIKER eingecheckt und einen Preis gewonnen hat, dann sollte der Screen Preis gewonnen angezeigt werden.

Erst wenn der Back-button gedrückt wurde sollte 12-checkin-erfolgreich.png angezeigt werden.

Der Button "Preis ansehen" am Screen 12-checkin-erfolgreich.png kann somit entfallen.

**Comment by starflower** [comment]
Ich bin dafür, um den User nach einem CheckIn nicht mit zu vielen Screens zu überfordern, falls er einen Preis gewonnen hat ,ein Popup mit "Gratuliere!"-Header anzuzeigen mit enthaltenem Preistext und Button "OK" welcher zum "CheckIn erfolgreich Screen" führt.

**Comment by Didi71** [comment]
ich glaub, dass uns der Gewinn eines Preises einen eigenen Screen (und kein Pop-up) spendieren sollten.
Die Radler radeln mit um Preise zu gewinnen - und der Gewinn eines Preises ist so quasi das Highlight!

Da würd' ich dann ehrer bei Gewinn eines Preises den "CheckIn erfolgreich Screen" gar nicht anzeigen.

**Comment by starflower** [comment]
Damit Christoph auch weiß, wie's weitergeht. Bei erfolgreichem CheckIn soll das Handy kurz vibrieren und wenn ein Preis gewonnen wurde folgende Info anzeigen: 
![14-preis](https://f.cloud.github.com/assets/499926/888973/164c9d64-fa17-11e2-8e03-3a2ccbbca792.png)
Sollte kein Preis gewonnen worden sein, würde ich den User zur Checkinseite weiterleiten.

**Comment by Didi71** [comment]
Schreib ma als Überschrift bitte: Herzlichen Glückwunsch!

Könnt' ma den Screen net a bissl feierlicher gestalten? Das schaut' jetzt ziemlich nüchtern aus und ist doch der Hauptgrund warum die Leut' mitradeln.     Einen weißen Lorbeerkranz drumrum ... keine Ahnung

Können wir auch den Button unten wegnehmen und stattdessen oben den BIKEbird als Back-Taste nutzen.
Oder generell wenn man auf den Screen tippt, dass es dann weiter geht mit den standard CheckIn-Infos.

**Comment by starflower** [comment]
So besser?

Bin auch dafür, dass man das mit Touch auf Screen wegmachen kann. Könnte man auch überlegen, ob man auf die Actionbar verzichtet.
![14-preis](https://f.cloud.github.com/assets/499926/892174/abfa5a92-fa79-11e2-993b-6cee6f689886.png)

**Comment by Didi71** [comment]
Ja. Tu ma den Actionbar weg. Das herzlichen Glückwunsch rauf - fertisch.

Am 01.08.2013 um 09:12 schrieb Matthias Kampitsch notifications@github.com:
