### ISSUE TITLE
Keine Zeit bei checkIn.php

### ISSUE THREAD

**Issue by skienzl** [Didi71/BIKELine-Android_old_tbd#30]
Bei "checkIn.php" kommt als date immer "0" zurück.

**Comment by Didi71** [comment]
grad getestet - sollte eigentlich funktionieren ...

**Comment by skienzl** [comment]
![bildschirmfoto 2013-07-31 um 20 17 56](https://f.cloud.github.com/assets/4992387/888428/9c9d0624-fa0d-11e2-88b6-7d72e1656a33.png)
Gerade wieder getestet. bei mir kommt keine zeit

**Comment by Didi71** [comment]
tschuldigung - bin ein vollhirni!
ich hab immer bei getCheckIns.php nachgeschaut.
jetzt sollt's aber gehen - schwöre!
