### ISSUE TITLE
Sony Xperia - Messages

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#32]
Beim Sony Xperia werden die Message-Boxen schräg angezeigt.
Der Hintergrund ist schwarz - der Texthintergrund weiß - und der Text schwarz.

**Comment by skienzl** [comment]
wenn das so ist bau mir das komplett selbst zusammen

**Comment by Didi71** [comment]
is leider so - wenn'st willst mach ich noch einen Snapshot, sobald ich meiner Tochter das Handy wieder entwenden kann.

**Comment by skienzl** [comment]
brauchst nit :) ich denk ich weis schon was is :)

**Comment by Didi71** [comment]
auch bei meinem Galaxy ist der Texthintergrund weiß und der Box-Hintergrund hellgrau - schaut schlimm aus!
