### ISSUE TITLE
Anmeldung fehlgeschlagen - UNKNOWN_EMAIL_ADDRESS

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#38]
Wenn loginBiker.php als Fehlermeldung UNKNOWN_EMAIL_ADDRESS zurück gibt, dann bitte folgende Meldung ausgeben:

Überschrift: "Anmeldung fehlgeschlagen".
Text: "Mit dieser Email-Adresse wurde noch niemand registriert!"

**Comment by skienzl** [comment]
du gibst ihn dem fall aber INVALID_EMAIL_ADDRESS (31) zurück. ist das auch ok?

**Comment by Didi71** [comment]
INVALID_EMAIL_ADDRESS wir zurückgegeben, wenn das Format der Email-Adresse ungültig ist.
Du kannst aber für beide Fehler obige Nachricht ausgeben.
