### ISSUE TITLE
PIN überprüfung läuft

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#46]
Nachdem die Message-Box: "PIN überprüfen ..." angezeigt wurde, stürzt die App ab.

**Comment by skienzl** [comment]
Bei welchem Handy und OS?
Am 02.08.2013 23:25 schrieb "Didi71" notifications@github.com:

**Comment by Didi71** [comment]
Samsung Galaxy
Andr. 4.0.3

**Comment by skienzl** [comment]
is das noch immer so?

**Comment by Didi71** [comment]
Scheint jetzt zu funktionieren.

Am 04.08.2013 um 20:10 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
das geht jetzt - denk ich.

Am 04.08.2013 20:10, schrieb skienzl:
