### ISSUE TITLE
Wähle Bundesland

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#48]
Auswahlbox wir nicht zentriert und zu klein dargestellt.

**Comment by skienzl** [comment]
hättest du einen screenshot von der auswahlbox?

**Comment by Didi71** [comment]
Bin nicht mehr am PC - schick ich dir morgen früh. Ich Denk, dass der Größenfehler daher rührt, dass die erste Zeile höher ist als die anderen.

Am 03.08.2013 um 00:56 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
so wie es auch auf den screenshots ist.  die erste zeile ist größer um sie als header zu erkennen. 

Am 03.08.2013 um 00:59 schrieb Didi71 notifications@github.com:

> Bin nicht mehr am PC - schick ich dir morgen früh. Ich Denk, dass der Größenfehler daher rührt, dass die erste Zeile höher ist als die anderen. 
> 
> Am 03.08.2013 um 00:56 schrieb skienzl notifications@github.com: 
> 
> > hättest du einen screenshot von der auswahlbox? 
> > 
> > — 
> > Reply to this email directly or view it on GitHub.
> > —
> > Reply to this email directly or view it on GitHub.

Stefan Kienzl
http://about.me/stefan.kienzl

**Comment by Didi71** [comment]
ist ja super, dass die erste Zeile größe ist - schaut auch toll aus. Ich meinte nur, dass das vielleicht der Grund sein könnte weshalb die Box nicht hoch genug ist.

![screenshot_2013-08-03-07-58-12](https://f.cloud.github.com/assets/5090129/905163/18762e06-fc02-11e2-9f9b-120054122110.png)
