### ISSUE TITLE
Wähle Schule

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#49]
Auswahlbox wird zu klein und nicht zentriert dargestellt (z.B. für Bundesland Kärnten)

**Comment by skienzl** [comment]
was meinst du mit "nicht zentriert dargestellt"?

**Comment by Didi71** [comment]
Sorry, hab erst jetzt gecheckt, dass du die Box immer knapp über der Liste anzeigst die auszufüllen ist - das passt perfekt.

Lediglich bei der Größe der Liste haperts ein wenig.

![2013_08_03_08 06 56](https://f.cloud.github.com/assets/5090129/905184/653ee696-fc03-11e2-88cb-ad9bf163d857.png)
