### ISSUE TITLE
Registrieren - Foto

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#5]
Es soll nur ein Foto aufgenommen werden können.
Die Auswahl eines Fotos aus der Gallerie sollte nicht möglich sein.

**Comment by skienzl** [comment]
geht klar :)  aber warum soll nur "foto aufnehmen" möglich sein?

**Comment by Didi71** [comment]
damit möchte ich verhindern, dass die BIKER irgendwelche Bildchen hochladen - auch in Hinblick auf Lizenzen. Ich möchte Fotos von den Gesichtern haben.

**Comment by clueckler** [comment]
Gibt es Android-Handy's ohne Kamera? Unter iOS müssten wir beim iPod nämlich aufpassen, der hat zwar eine Photolib aber keine Kamera!

**Comment by Didi71** [comment]
Händies und dergleichen ohne Kamera können wir ausschließen - die können auch den QR-Code nicht scannen.

Am 30.07.2013 um 14:31 schrieb Christoph Lückler notifications@github.com:
