### ISSUE TITLE
CheckPoints ausrichten - Position merken

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#56]
Die App sollte beim CheckIn und bei das CheckPoint Map die aktuelle Position des Nutzers speichern.

Wenn beim Aufruf von CheckPoints keine aktuelle Position verfügbar ist, dann sollte die Map anhand der gespeicherten Position ausgerichtet werden.

Der initiale Zoom sollte so gewählt werden, dass die Map einen Bereich von 5-10km um die aktuelle Position anzeigt.

**Comment by skienzl** [comment]
und was soll angezeigt werden wenn die app das erste mal gestartet wird und es keine position gibt?

**Comment by Didi71** [comment]
Kaindorf bei Hartberg

Am 03.08.2013 um 00:50 schrieb skienzl notifications@github.com:
