### ISSUE TITLE
CheckPoints + WebPages

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#57]
getCheckPoints.php liefert nun zu jedem CheckPoint auch die WebPage ("webPage") des CheckPoints als auch die webPage eines etwaigen Events ("eventWebPage")

@Matthias: könntest du bitte überlegen, wie die Infobox aussehen müsste, damit man via Infobox zur WebPage des CheckPoints bzw. zur WebPage des Events wechseln könnte.

**Comment by starflower** [comment]
Wann seh ich diese Infobox?

**Comment by Didi71** [comment]
Wenn du den CheckPoint antippst

**Comment by starflower** [comment]
Was hältst du von einem Pfeil?
http://i.stack.imgur.com/fkGQQ.png

**Comment by Didi71** [comment]
Passt. Einen für den Checkpoint und einen ev. Für das Event.

Danke
Didi

Am 03.08.2013 um 00:35 schrieb Matthias Kampitsch notifications@github.com:

**Comment by starflower** [comment]
Das heißt, pro Infowindow kann es zwei Pfeile geben?

**Comment by Didi71** [comment]
Ja

Am 03.08.2013 um 09:07 schrieb Matthias Kampitsch notifications@github.com:

**Comment by starflower** [comment]
Das sehe ich als Problem. Infowindow ist mitunter sehr klein und der User ist gewohnt, dass er das die ganze Bubble drücken kann. Die Information so darzustellen, dass da zwei unterschiedliche Links drin sind, ist mitunter sehr schwierig. Vorschlag: Bei Touch auf das Infowindow kommt bei einem Link gleich die hinterlegte Website, bei zwei hinterlegten Links kommt ein Auswahl Popup "Checkpoint Website besuchen" & "Event Website besuchen"

**Comment by Didi71** [comment]
perfekt!

Am 03.08.2013 09:39, schrieb Matthias Kampitsch:

**Comment by skienzl** [comment]
ich hab das jetzt einmal so umgesetzt. funktioniert auch. aber ich denke ein indikator für eine website wäre doch ganz nützlich für den user.

**Comment by starflower** [comment]
Gibt's da keinen Standard Pfeil?  

Am Samstag, 03. August 2013 um 11:42 schrieb skienzl:

**Comment by skienzl** [comment]
i check das und werds machen :)
