### ISSUE TITLE
Facts - ActionBar - Icons

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#58]
Mags dir bitte mal den ActionBar und die Icons anschaun. 

Aus meines Sicht passen die Icon-Größen und Positionen nicht ganz.

**Comment by skienzl** [comment]
ist aber die standard position.

**Comment by Didi71** [comment]
für mein Gefühl gehören die CheckIns a bissl runter und das Geschenk a bissl rauf.
