### ISSUE TITLE
Preis-Screen wird nicht angezeigt

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#61]
Manchmal ertönt die Fanfare, aber der Preis-Screen wird nicht angezeigt.

**Comment by skienzl** [comment]
wenn kein preis da ist kommt auch kein screen. zumindest habe ich und matthias das so verstanden. langsam sollten wir uns einiges wie welche screens genau sind...

**Comment by Didi71** [comment]
Samsung Galaxy GT-I9100
Andr. 4.0.3

**Comment by skienzl** [comment]
was ist jetzt mit dem screen?

**Comment by Didi71** [comment]
Was meinst du mit jetzt. Gibt's ne neue Version?

Am 03.08.2013 um 00:37 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
nein. ich meine wie ich das jetzt machen soll. weil eigentlich kam ja der andere weg und es sollte nur ein screen kommen wenn ein preis dabei ist. soll das jetzt doch noch ein screen kommen, auch wenn kein preis dabei ist?

**Comment by Didi71** [comment]
Nö! Der Preisscreen soll nur angezeigt werden, wenn es auch einen Preis gibt. 

Das derzeitige Problem ist, dass manchmal eine Fanfare gespielt wird, und danach der Preisdialog nicht angezeigt wird.

Oder spielst du die Fanfare immer? Sollte nur tröten, wenn ein Preis gewonnen wurde.

Am 03.08.2013 um 00:45 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
die Fanfare kommt derzeit immer.

**Comment by skienzl** [comment]
habs umgestellt

**Comment by Didi71** [comment]
Bitte nur fanfaren wenn ein Preis gewonnen wurde.

Am 03.08.2013 um 00:50 schrieb skienzl notifications@github.com:
