### ISSUE TITLE
Sony Xperia - Fact Listen

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#62]
Wenn man am Sony Xperia in der Fact Listen scrollt, dann werden die Listen komplett weiss und zeigen nix mehr an.

**Comment by skienzl** [comment]
was ist das den genau für ein xperia mit welchem OS?

**Comment by Didi71** [comment]
sony xperia: ST25i
android 2.3.7

**Comment by Didi71** [comment]
ist noch immer so!

**Comment by skienzl** [comment]
das sony is sowieso ein wahnsinn :D aber da kann ich nur probieren ;)
