### ISSUE TITLE
CheckPoints-Map: Aktueller Standort

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#64]
Wenn es möglich wär, wäre es hilfreich die Box (rechts oben: aktueller Standort) nur dann anzuzeigen, wenn ein aktueller Standort ermittelt werden kann.

**Comment by skienzl** [comment]
Der Standort kommt normal immer mach 5 sec. Für diese Zeit zahlt sich ein
eigener Position listener normal nit aus.
Am 03.08.2013 20:24 schrieb "Didi71" notifications@github.com:

**Comment by Didi71** [comment]
ok!
