### ISSUE TITLE
CheckPoints-Map: Aktueller Standort Zoom

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#65]
Wenn möglich, dann wäre toll, wenn der Mapbereich, wenn man auf den Button (rechts oben Aktueller Standort) tippt, einen Mapbereich von 5-10km anzeigen würden.

**Comment by skienzl** [comment]
die funktion bei diesem button selbst etwas zu machen kommt leider erst in der neuen google maps version. 

https://code.google.com/p/gmaps-api-issues/issues/detail?id=4789

**Comment by Didi71** [comment]
ok, dann später mal!
