### ISSUE TITLE
Team beitreten - Auswahllisten Timeout

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#70]
Manchmal wird nur die MessageBox angezeigt, dass etwas geladen wird, und nach einer gewissen Zeit verschwindet die MessageBox ohne das die entsprechende Auswahlliste erscheint

**Comment by skienzl** [comment]
ist das noch so?

**Comment by Didi71** [comment]
bei meinem Galaxy funktioniert bei der Anmeldung die Auswahl eines Teams 
nicht.
Da stürzt die App regelmäßig ab.

Am 05.08.2013 10:03, schrieb skienzl:

**Comment by Didi71** [comment]
Fehler ist nicht mehr aufgetreten!
