### ISSUE TITLE
Profilbildergröße

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#79]
Die hochgeladenen Profilbilder sollten eine Größe von 240 x 360 Pixel haben

**Comment by skienzl** [comment]
ein genaues maß wird eigentlich schwer bei jeder smartphones. weil die bilder ja nicht immer das gleich verhältnis haben und dadurch das bild zugeschnitten werden muss

**Comment by Didi71** [comment]
ich hab's bei der BIKEline so gelöst, dass ich hochgeladene Bilder 
zunächst im richtigen Verhältnis beschneide und danach auf die 
gewünschte Auflösung skaliere.

Am 05.08.2013 10:03, schrieb skienzl:

**Comment by skienzl** [comment]
Das ist mir schon klar. Aber ich meine du entscheidest ja somit für den
user was vom Bild weggeschnitten wird. Weil man ja nicht sagen kann wo der
Fokus am Bild liegt.
Am 05.08.2013 15:51 schrieb "Didi71" notifications@github.com:

**Comment by Didi71** [comment]
ja - das mach ich! hehe - und wenn der User sieht was ich alles 
weggeschnitten hab und ihm das nicht passt, dann muss er eben nochmals 
schießen.

Hilfreich in diesem Zusammenhang wäre, wenn der User das Bild im 
Portrait-Format aufnehmen würde - dann würden wir nicht soviel 
wegschneiden. Geht das bzw. Kann man den User darauf hinweise im 
Portrait Format aufzunehmen?

Am 05.08.2013 16:18, schrieb skienzl:

**Comment by Didi71** [comment]
Könnte man nicht so ein Overlay drüberlegen. Dann wüsste der User, dass es Portrait sein soll, und auch der Kopf hätte die richtige Größe.

![test](https://f.cloud.github.com/assets/5090129/910478/39165b38-fddb-11e2-9240-7f9cc82c7023.jpg)

**Comment by Didi71** [comment]
@matthias - das Overlay müsste natürlich schöner sein.

**Comment by skienzl** [comment]
der müsste halt ein Rechteck mit dem gleichen wie  240 x 360 sein denke ich. nichtsdestotrotz ist dann quasi eine eigen camera app für das app ;) aber ich schau einmal was ich machen kann

**Comment by skienzl** [comment]
glaubst du das 1:1 format nicht besser ausschaut als 1:1,5 ?

**Comment by Didi71** [comment]
1:1 ist auch ok, dann muss ich eben die Webpage anpassen.

Am 05.08.2013 um 17:32 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
Kommando Retour. Ich zeig auf der Webpage parallel dazu die Fotos der Bikeliner, und die sind 1:1,5. deshalb sollten es auch diese Fotos sein.

Am 05.08.2013 um 17:32 schrieb skienzl notifications@github.com:
