### ISSUE TITLE
loginBiker.php fehlermeldung

### ISSUE THREAD

**Issue by skienzl** [Didi71/BIKELine-Android_old_tbd#80]
loginBiker.php wirft folgenden Fehler:

<br />
<b>Fatal error</b>:  require_once() [<a href='function.require'>function.require</a>]: Failed opening required '../../bb/bikebird/PhpScripts/PHPMailer/class.phpmailer.php' (include_path='.:/usr/share/pear') in <b>/home/.sites/228/site1541/web/BIKElineCheckPoint/TestApp-Scripts/loginBiker.php</b> on line <b>9</b><br />

**Comment by Didi71** [comment]
Uiiii!

Hab heut' am Server aufgeräumt - anscheinend ein bisschen zu tolle.
Jetzt sollte es wieder gehen - Kannst mir bitte kurz Bescheid geben.

Sorry & Danke
Didi

Am 04.08.2013 17:08, schrieb skienzl:

**Comment by skienzl** [comment]
Kein Problem :) geht jetzt e wieder. Gerade probiert.
Am 04.08.2013 17:31 schrieb "Didi71" notifications@github.com:
