### ISSUE TITLE
CheckPoints - Map - zeigt keine CheckPoints

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#82]
Manchmal kommt es vor, dass auf der Map keine CheckPoints angezeigt werden

**Comment by Didi71** [comment]
das ist am Samsung Galaxy immer noch so!

Wenn keine CheckPoints angezeigt werden, dann wird zuvor die MessageBox länger angezeigt. Könnte sein, dass es hier zu einem Timeout kommt und die CheckPoints dann bei Ablauf des Timeouts nicht angezeigt werden?

**Comment by skienzl** [comment]
es liegt denke ich bestimmt am Timeout. ich hab das Timeout jetzt von 5 auf 10 sekunde.

**Comment by Didi71** [comment]
Sollten wir für den Fall eines Timeouts nicht eine MessageBox anzeigen, dass keine Verbindung zum Server hergestellt werden konnte.

Am 08.08.2013 um 19:33 schrieb skienzl notifications@github.com:
