### ISSUE TITLE
Bereits Mitglied - Anmelden Button

### ISSUE THREAD

**Issue by Didi71** [Didi71/BIKELine-Android_old_tbd#97]
Den Anmelden-Button bitte ganz unten anzeigen.

**Comment by skienzl** [comment]
ist der noch nicht ganz unten?

**Comment by Didi71** [comment]
Hab's nur mit Samsung getestet - dort ist er unten. war mir nicht sicher ob er auch bei anderen Displays unten ist.

Am 08.08.2013 um 10:14 schrieb skienzl notifications@github.com:
